; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.21005.1 

	TITLE	C:\Projets\SUDOKU\SUDOKU\SUDOKU\SUDOKUDlg.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

PUBLIC	?OnPaint@CSUDOKUDlg@@IAEXXZ			; CSUDOKUDlg::OnPaint
PUBLIC	?OnQueryDragIcon@CSUDOKUDlg@@IAEPAUHICON__@@XZ	; CSUDOKUDlg::OnQueryDragIcon
PUBLIC	?OnBnClickedOk@CSUDOKUDlg@@QAEXXZ		; CSUDOKUDlg::OnBnClickedOk
PUBLIC	?OnBnClickedCancel@CSUDOKUDlg@@QAEXXZ		; CSUDOKUDlg::OnBnClickedCancel
PUBLIC	?OnBnClickedButton1@CSUDOKUDlg@@QAEXXZ		; CSUDOKUDlg::OnBnClickedButton1
PUBLIC	?OnBnClickedButton2@CSUDOKUDlg@@QAEXXZ		; CSUDOKUDlg::OnBnClickedButton2
PUBLIC	?m_nLevel@CTrace@ATL@@1IA			; ATL::CTrace::m_nLevel
PUBLIC	?m_nCategory@CTrace@ATL@@1IA			; ATL::CTrace::m_nCategory
PUBLIC	?m_nLastCategory@CTrace@ATL@@1IA		; ATL::CTrace::m_nLastCategory
PUBLIC	?m_nMap@CTrace@ATL@@1PAUCategoryMap@12@A	; ATL::CTrace::m_nMap
EXTRN	?GetThisMessageMap@CDialogEx@@KGPBUAFX_MSGMAP@@XZ:PROC ; CDialogEx::GetThisMessageMap
;	COMDAT ?m_nLevel@CTrace@ATL@@1IA
_BSS	SEGMENT
?m_nLevel@CTrace@ATL@@1IA DD 01H DUP (?)		; ATL::CTrace::m_nLevel
_BSS	ENDS
;	COMDAT ?m_nLastCategory@CTrace@ATL@@1IA
_BSS	SEGMENT
?m_nLastCategory@CTrace@ATL@@1IA DD 01H DUP (?)		; ATL::CTrace::m_nLastCategory
_BSS	ENDS
;	COMDAT ?m_nMap@CTrace@ATL@@1PAUCategoryMap@12@A
_BSS	SEGMENT
?m_nMap@CTrace@ATL@@1PAUCategoryMap@12@A DB 02080H DUP (?) ; ATL::CTrace::m_nMap
_BSS	ENDS
;	COMDAT ?m_nCategory@CTrace@ATL@@1IA
_DATA	SEGMENT
?m_nCategory@CTrace@ATL@@1IA DD 0ffffffffH		; ATL::CTrace::m_nCategory
_DATA	ENDS
CONST	SEGMENT
?_messageEntries@?1??GetThisMessageMap@CSUDOKUDlg@@KGPBUAFX_MSGMAP@@XZ@4QBUAFX_MSGMAP_ENTRY@@B DD 0fH ; `CSUDOKUDlg::GetThisMessageMap'::`2'::_messageEntries
	DD	00H
	DD	00H
	DD	00H
	DD	013H
	DD	FLAT:?OnPaint@CSUDOKUDlg@@IAEXXZ
	DD	037H
	DD	00H
	DD	00H
	DD	00H
	DD	029H
	DD	FLAT:?OnQueryDragIcon@CSUDOKUDlg@@IAEPAUHICON__@@XZ
	DD	0111H
	DD	00H
	DD	01H
	DD	01H
	DD	03aH
	DD	FLAT:?OnBnClickedOk@CSUDOKUDlg@@QAEXXZ
	DD	0111H
	DD	00H
	DD	02H
	DD	02H
	DD	03aH
	DD	FLAT:?OnBnClickedCancel@CSUDOKUDlg@@QAEXXZ
	DD	0111H
	DD	00H
	DD	0439H
	DD	0439H
	DD	03aH
	DD	FLAT:?OnBnClickedButton1@CSUDOKUDlg@@QAEXXZ
	DD	0111H
	DD	00H
	DD	043aH
	DD	043aH
	DD	03aH
	DD	FLAT:?OnBnClickedButton2@CSUDOKUDlg@@QAEXXZ
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
?messageMap@?1??GetThisMessageMap@CSUDOKUDlg@@KGPBUAFX_MSGMAP@@XZ@4U3@B DD FLAT:?GetThisMessageMap@CDialogEx@@KGPBUAFX_MSGMAP@@XZ ; `CSUDOKUDlg::GetThisMessageMap'::`2'::messageMap
	DD	FLAT:?_messageEntries@?1??GetThisMessageMap@CSUDOKUDlg@@KGPBUAFX_MSGMAP@@XZ@4QBUAFX_MSGMAP_ENTRY@@B
CONST	ENDS
PUBLIC	??0?$CTraceCategoryEx@$0CAAA@$0A@@ATL@@QAE@PB_W@Z ; ATL::CTraceCategoryEx<8192,0>::CTraceCategoryEx<8192,0>
PUBLIC	??0?$CTraceCategoryEx@$0CAAAA@$0A@@ATL@@QAE@PB_W@Z ; ATL::CTraceCategoryEx<131072,0>::CTraceCategoryEx<131072,0>
PUBLIC	?RegisterCategory@CTrace@ATL@@SAXPB_WI@Z	; ATL::CTrace::RegisterCategory
PUBLIC	??0CRect@@QAE@XZ				; CRect::CRect
PUBLIC	?Width@CRect@@QBEHXZ				; CRect::Width
PUBLIC	?Height@CRect@@QBEHXZ				; CRect::Height
PUBLIC	?__autoclassinit2@CPaintDC@@QAEXI@Z		; CPaintDC::__autoclassinit2
PUBLIC	??1CDialogEx@@UAE@XZ				; CDialogEx::~CDialogEx
PUBLIC	??0CSUDOKUDlg@@QAE@PAVCWnd@@@Z			; CSUDOKUDlg::CSUDOKUDlg
PUBLIC	?DoDataExchange@CSUDOKUDlg@@MAEXPAVCDataExchange@@@Z ; CSUDOKUDlg::DoDataExchange
PUBLIC	?OnInitDialog@CSUDOKUDlg@@MAEHXZ		; CSUDOKUDlg::OnInitDialog
PUBLIC	?GetThisMessageMap@CSUDOKUDlg@@KGPBUAFX_MSGMAP@@XZ ; CSUDOKUDlg::GetThisMessageMap
PUBLIC	?GetMessageMap@CSUDOKUDlg@@MBEPBUAFX_MSGMAP@@XZ	; CSUDOKUDlg::GetMessageMap
PUBLIC	??1CSUDOKUDlg@@UAE@XZ				; CSUDOKUDlg::~CSUDOKUDlg
PUBLIC	??_GCSUDOKUDlg@@UAEPAXI@Z			; CSUDOKUDlg::`scalar deleting destructor'
PUBLIC	??_C@_15GANGMFKL@?$AA?$CF?$AAs?$AA?$AA@		; `string'
PUBLIC	?atlTraceException@ATL@@3V?$CTraceCategoryEx@$0CAAA@$0A@@1@A ; ATL::atlTraceException
PUBLIC	??_C@_1CE@IMMADNAP@?$AAa?$AAt?$AAl?$AAT?$AAr?$AAa?$AAc?$AAe?$AAE?$AAx?$AAc?$AAe?$AAp?$AAt?$AAi?$AAo?$AAn?$AA?$AA@ ; `string'
PUBLIC	?atlTraceString@ATL@@3V?$CTraceCategoryEx@$0CAAAA@$0A@@1@A ; ATL::atlTraceString
PUBLIC	??_C@_1BO@GMLILNDJ@?$AAa?$AAt?$AAl?$AAT?$AAr?$AAa?$AAc?$AAe?$AAS?$AAt?$AAr?$AAi?$AAn?$AAg?$AA?$AA@ ; `string'
PUBLIC	??_C@_1EO@EBPPKGOM@?$AAf?$AAa?$AAl?$AAs?$AAe?$AA?5?$AA?$CG?$AA?$CG?$AA?5?$AA?$CC?$AAT?$AAo?$AAo?$AA?5?$AAm?$AAa?$AAn?$AAy?$AA?5?$AAc?$AAa?$AAt?$AAe?$AAg?$AAo?$AAr?$AAi?$AAe?$AAs?$AA?5?$AAd?$AAe@ ; `string'
PUBLIC	??_C@_1KC@GEMPEEJK@?$AAc?$AA?3?$AA?2?$AAp?$AAr?$AAo?$AAg?$AAr?$AAa?$AAm?$AA?5?$AAf?$AAi?$AAl?$AAe?$AAs?$AA?5?$AA?$CI?$AAx?$AA8?$AA6?$AA?$CJ?$AA?2?$AAm?$AAi?$AAc?$AAr?$AAo?$AAs?$AAo?$AAf?$AAt@ ; `string'
PUBLIC	??_C@_11LOCGONAA@?$AA?$AA@			; `string'
PUBLIC	??_R1A@?0A@EA@CObject@@8			; CObject::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVCObject@@@8				; CObject `RTTI Type Descriptor'
PUBLIC	??_R3CObject@@8					; CObject::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CObject@@8					; CObject::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CDialog@@8			; CDialog::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVCDialog@@@8				; CDialog `RTTI Type Descriptor'
PUBLIC	??_R3CDialog@@8					; CDialog::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CDialog@@8					; CDialog::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CWnd@@8				; CWnd::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVCWnd@@@8				; CWnd `RTTI Type Descriptor'
PUBLIC	??_R3CWnd@@8					; CWnd::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CWnd@@8					; CWnd::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CCmdTarget@@8			; CCmdTarget::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVCCmdTarget@@@8				; CCmdTarget `RTTI Type Descriptor'
PUBLIC	??_R3CCmdTarget@@8				; CCmdTarget::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CCmdTarget@@8				; CCmdTarget::`RTTI Base Class Array'
PUBLIC	??_7CSUDOKUDlg@@6B@				; CSUDOKUDlg::`vftable'
PUBLIC	?__LINE__Var@?1??OnBnClickedOk@CSUDOKUDlg@@QAEXXZ@4JA ; `CSUDOKUDlg::OnBnClickedOk'::`2'::__LINE__Var
PUBLIC	??_C@_0CO@COLFEFNB@c?3?2projets?2sudoku?2sudoku?2sudoku?2@ ; `string'
PUBLIC	??_C@_17IBCNDFFO@?$AAF?$AAi?$AAn?$AA?$AA@	; `string'
PUBLIC	?__LINE__Var@?1??OnBnClickedButton2@CSUDOKUDlg@@QAEXXZ@4JA ; `CSUDOKUDlg::OnBnClickedButton2'::`2'::__LINE__Var
PUBLIC	??_R4CSUDOKUDlg@@6B@				; CSUDOKUDlg::`RTTI Complete Object Locator'
PUBLIC	??_R0?AVCSUDOKUDlg@@@8				; CSUDOKUDlg `RTTI Type Descriptor'
PUBLIC	??_R3CSUDOKUDlg@@8				; CSUDOKUDlg::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CSUDOKUDlg@@8				; CSUDOKUDlg::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CSUDOKUDlg@@8			; CSUDOKUDlg::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R1A@?0A@EA@CDialogEx@@8			; CDialogEx::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVCDialogEx@@@8				; CDialogEx `RTTI Type Descriptor'
PUBLIC	??_R3CDialogEx@@8				; CDialogEx::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CDialogEx@@8				; CDialogEx::`RTTI Base Class Array'
EXTRN	__imp__wcscpy_s:PROC
EXTRN	__imp__SetDlgItemTextW@12:PROC
EXTRN	__imp__GetSystemMetrics@4:PROC
EXTRN	__imp___CrtDbgReportW:PROC
EXTRN	??3CObject@@SGXPAX@Z:PROC			; CObject::operator delete
EXTRN	?Serialize@CObject@@UAEXAAVCArchive@@@Z:PROC	; CObject::Serialize
EXTRN	__imp_?GetBuffer@?$CSimpleStringT@_W$00@ATL@@QAEPA_WXZ:PROC
EXTRN	__imp_??0?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@PB_W@Z:PROC
EXTRN	__imp_??1?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ:PROC
EXTRN	??2@YAPAXIPBDH@Z:PROC				; operator new
EXTRN	??3@YAXPAXPBDH@Z:PROC				; operator delete
EXTRN	??1CBrush@@UAE@XZ:PROC				; CBrush::~CBrush
EXTRN	?GetSafeHdc@CDC@@QBEPAUHDC__@@XZ:PROC		; CDC::GetSafeHdc
EXTRN	?DrawIcon@CDC@@QAEHHHPAUHICON__@@@Z:PROC	; CDC::DrawIcon
EXTRN	??0CPaintDC@@QAE@PAVCWnd@@@Z:PROC		; CPaintDC::CPaintDC
EXTRN	??1CPaintDC@@UAE@XZ:PROC			; CPaintDC::~CPaintDC
EXTRN	?IsInvokeAllowed@CCmdTarget@@UAEHJ@Z:PROC	; CCmdTarget::IsInvokeAllowed
EXTRN	?GetDispatchIID@CCmdTarget@@UAEHPAU_GUID@@@Z:PROC ; CCmdTarget::GetDispatchIID
EXTRN	?GetTypeInfoCount@CCmdTarget@@UAEIXZ:PROC	; CCmdTarget::GetTypeInfoCount
EXTRN	?GetTypeLibCache@CCmdTarget@@UAEPAVCTypeLibCache@@XZ:PROC ; CCmdTarget::GetTypeLibCache
EXTRN	?GetTypeLib@CCmdTarget@@UAEJKPAPAUITypeLib@@@Z:PROC ; CCmdTarget::GetTypeLib
EXTRN	?GetCommandMap@CCmdTarget@@MBEPBUAFX_OLECMDMAP@@XZ:PROC ; CCmdTarget::GetCommandMap
EXTRN	?GetDispatchMap@CCmdTarget@@MBEPBUAFX_DISPMAP@@XZ:PROC ; CCmdTarget::GetDispatchMap
EXTRN	?GetConnectionMap@CCmdTarget@@MBEPBUAFX_CONNECTIONMAP@@XZ:PROC ; CCmdTarget::GetConnectionMap
EXTRN	?GetEventSinkMap@CCmdTarget@@MBEPBUAFX_EVENTSINKMAP@@XZ:PROC ; CCmdTarget::GetEventSinkMap
EXTRN	?OnCreateAggregates@CCmdTarget@@UAEHXZ:PROC	; CCmdTarget::OnCreateAggregates
EXTRN	?GetInterfaceHook@CCmdTarget@@UAEPAUIUnknown@@PBX@Z:PROC ; CCmdTarget::GetInterfaceHook
EXTRN	?GetExtraConnectionPoints@CCmdTarget@@MAEHPAVCPtrArray@@@Z:PROC ; CCmdTarget::GetExtraConnectionPoints
EXTRN	?GetConnectionHook@CCmdTarget@@MAEPAUIConnectionPoint@@ABU_GUID@@@Z:PROC ; CCmdTarget::GetConnectionHook
EXTRN	?PreSubclassWindow@CWnd@@UAEXXZ:PROC		; CWnd::PreSubclassWindow
EXTRN	?Create@CWnd@@UAEHPB_W0KABUtagRECT@@PAV1@IPAUCCreateContext@@@Z:PROC ; CWnd::Create
EXTRN	?CreateEx@CWnd@@UAEHKPB_W0KHHHHPAUHWND__@@PAUHMENU__@@PAX@Z:PROC ; CWnd::CreateEx
EXTRN	?CreateEx@CWnd@@UAEHKPB_W0KABUtagRECT@@PAV1@IPAX@Z:PROC ; CWnd::CreateEx
EXTRN	?DestroyWindow@CWnd@@UAEHXZ:PROC		; CWnd::DestroyWindow
EXTRN	?PreCreateWindow@CWnd@@UAEHAAUtagCREATESTRUCTW@@@Z:PROC ; CWnd::PreCreateWindow
EXTRN	?CalcWindowRect@CWnd@@UAEXPAUtagRECT@@I@Z:PROC	; CWnd::CalcWindowRect
EXTRN	?GetDlgItem@CWnd@@QBEPAV1@H@Z:PROC		; CWnd::GetDlgItem
EXTRN	?SendMessageW@CWnd@@QBEJIIJ@Z:PROC		; CWnd::SendMessageW
EXTRN	?SetWindowTextW@CWnd@@QAEXPB_W@Z:PROC		; CWnd::SetWindowTextW
EXTRN	?GetMenu@CWnd@@UBEPAVCMenu@@XZ:PROC		; CWnd::GetMenu
EXTRN	?SetMenu@CWnd@@UAEHPAVCMenu@@@Z:PROC		; CWnd::SetMenu
EXTRN	?IsIconic@CWnd@@QBEHXZ:PROC			; CWnd::IsIconic
EXTRN	?GetClientRect@CWnd@@QBEXPAUtagRECT@@@Z:PROC	; CWnd::GetClientRect
EXTRN	?EnableToolTips@CWnd@@QAEHH@Z:PROC		; CWnd::EnableToolTips
EXTRN	?OnToolHitTest@CWnd@@UBEHVCPoint@@PAUtagTOOLINFOW@@@Z:PROC ; CWnd::OnToolHitTest
EXTRN	?EnableWindow@CWnd@@QAEHH@Z:PROC		; CWnd::EnableWindow
EXTRN	?GetScrollBarCtrl@CWnd@@UBEPAVCScrollBar@@H@Z:PROC ; CWnd::GetScrollBarCtrl
EXTRN	?SetIcon@CWnd@@QAEPAUHICON__@@PAU2@H@Z:PROC	; CWnd::SetIcon
EXTRN	?WinHelpW@CWnd@@UAEXKI@Z:PROC			; CWnd::WinHelpW
EXTRN	?HtmlHelpW@CWnd@@UAEXKI@Z:PROC			; CWnd::HtmlHelpW
EXTRN	?WinHelpInternal@CWnd@@UAEXKI@Z:PROC		; CWnd::WinHelpInternal
EXTRN	?ContinueModal@CWnd@@UAEHXZ:PROC		; CWnd::ContinueModal
EXTRN	?EndModalLoop@CWnd@@UAEXH@Z:PROC		; CWnd::EndModalLoop
EXTRN	?OnDrawIconicThumbnailOrLivePreview@CWnd@@UAEXAAVCDC@@VCRect@@VCSize@@HAAH@Z:PROC ; CWnd::OnDrawIconicThumbnailOrLivePreview
EXTRN	?GetInterfaceMap@CWnd@@MBEPBUAFX_INTERFACEMAP@@XZ:PROC ; CWnd::GetInterfaceMap
EXTRN	?EnsureStdObj@CWnd@@UAEJXZ:PROC			; CWnd::EnsureStdObj
EXTRN	?get_accParent@CWnd@@UAEJPAPAUIDispatch@@@Z:PROC ; CWnd::get_accParent
EXTRN	?get_accChildCount@CWnd@@UAEJPAJ@Z:PROC		; CWnd::get_accChildCount
EXTRN	?get_accChild@CWnd@@UAEJUtagVARIANT@@PAPAUIDispatch@@@Z:PROC ; CWnd::get_accChild
EXTRN	?get_accName@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z:PROC ; CWnd::get_accName
EXTRN	?get_accValue@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z:PROC ; CWnd::get_accValue
EXTRN	?get_accDescription@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z:PROC ; CWnd::get_accDescription
EXTRN	?get_accRole@CWnd@@UAEJUtagVARIANT@@PAU2@@Z:PROC ; CWnd::get_accRole
EXTRN	?get_accState@CWnd@@UAEJUtagVARIANT@@PAU2@@Z:PROC ; CWnd::get_accState
EXTRN	?get_accHelp@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z:PROC ; CWnd::get_accHelp
EXTRN	?get_accHelpTopic@CWnd@@UAEJPAPA_WUtagVARIANT@@PAJ@Z:PROC ; CWnd::get_accHelpTopic
EXTRN	?get_accKeyboardShortcut@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z:PROC ; CWnd::get_accKeyboardShortcut
EXTRN	?get_accFocus@CWnd@@UAEJPAUtagVARIANT@@@Z:PROC	; CWnd::get_accFocus
EXTRN	?get_accSelection@CWnd@@UAEJPAUtagVARIANT@@@Z:PROC ; CWnd::get_accSelection
EXTRN	?get_accDefaultAction@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z:PROC ; CWnd::get_accDefaultAction
EXTRN	?accSelect@CWnd@@UAEJJUtagVARIANT@@@Z:PROC	; CWnd::accSelect
EXTRN	?accLocation@CWnd@@UAEJPAJ000UtagVARIANT@@@Z:PROC ; CWnd::accLocation
EXTRN	?accNavigate@CWnd@@UAEJJUtagVARIANT@@PAU2@@Z:PROC ; CWnd::accNavigate
EXTRN	?accHitTest@CWnd@@UAEJJJPAUtagVARIANT@@@Z:PROC	; CWnd::accHitTest
EXTRN	?accDoDefaultAction@CWnd@@UAEJUtagVARIANT@@@Z:PROC ; CWnd::accDoDefaultAction
EXTRN	?put_accName@CWnd@@UAEJUtagVARIANT@@PA_W@Z:PROC	; CWnd::put_accName
EXTRN	?put_accValue@CWnd@@UAEJUtagVARIANT@@PA_W@Z:PROC ; CWnd::put_accValue
EXTRN	?SetProxy@CWnd@@UAEJPAUIAccessibleProxy@@@Z:PROC ; CWnd::SetProxy
EXTRN	?CreateAccessibleProxy@CWnd@@UAEJIJPAJ@Z:PROC	; CWnd::CreateAccessibleProxy
EXTRN	?OnNotify@CWnd@@MAEHIJPAJ@Z:PROC		; CWnd::OnNotify
EXTRN	?GetSuperWndProcAddr@CWnd@@MAEPAP6GJPAUHWND__@@IIJ@ZXZ:PROC ; CWnd::GetSuperWndProcAddr
EXTRN	?DoDataExchange@CWnd@@MAEXPAVCDataExchange@@@Z:PROC ; CWnd::DoDataExchange
EXTRN	?BeginModalState@CWnd@@UAEXXZ:PROC		; CWnd::BeginModalState
EXTRN	?EndModalState@CWnd@@UAEXXZ:PROC		; CWnd::EndModalState
EXTRN	?OnAmbientProperty@CWnd@@UAEHPAVCOleControlSite@@JPAUtagVARIANT@@@Z:PROC ; CWnd::OnAmbientProperty
EXTRN	?WindowProc@CWnd@@MAEJIIJ@Z:PROC		; CWnd::WindowProc
EXTRN	?OnWndMsg@CWnd@@MAEHIIJPAJ@Z:PROC		; CWnd::OnWndMsg
EXTRN	?DefWindowProcW@CWnd@@MAEJIIJ@Z:PROC		; CWnd::DefWindowProcW
EXTRN	?PostNcDestroy@CWnd@@MAEXXZ:PROC		; CWnd::PostNcDestroy
EXTRN	?OnChildNotify@CWnd@@MAEHIIJPAJ@Z:PROC		; CWnd::OnChildNotify
EXTRN	?OnTouchInputs@CWnd@@MAEHIPAUtagTOUCHINPUT@@@Z:PROC ; CWnd::OnTouchInputs
EXTRN	?OnTouchInput@CWnd@@MAEHVCPoint@@HHPAUtagTOUCHINPUT@@@Z:PROC ; CWnd::OnTouchInput
EXTRN	?GetGestureStatus@CWnd@@MAEKVCPoint@@@Z:PROC	; CWnd::GetGestureStatus
EXTRN	?OnGestureZoom@CWnd@@MAEHVCPoint@@J@Z:PROC	; CWnd::OnGestureZoom
EXTRN	?OnGesturePan@CWnd@@MAEHVCPoint@@0@Z:PROC	; CWnd::OnGesturePan
EXTRN	?OnGestureRotate@CWnd@@MAEHVCPoint@@N@Z:PROC	; CWnd::OnGestureRotate
EXTRN	?OnGestureTwoFingerTap@CWnd@@MAEHVCPoint@@@Z:PROC ; CWnd::OnGestureTwoFingerTap
EXTRN	?OnGesturePressAndTap@CWnd@@MAEHVCPoint@@J@Z:PROC ; CWnd::OnGesturePressAndTap
EXTRN	?IsFrameWnd@CWnd@@UBEHXZ:PROC			; CWnd::IsFrameWnd
EXTRN	?OnFinalRelease@CWnd@@UAEXXZ:PROC		; CWnd::OnFinalRelease
EXTRN	?CreateControlContainer@CWnd@@MAEHPAPAVCOleControlContainer@@@Z:PROC ; CWnd::CreateControlContainer
EXTRN	?CreateControlSite@CWnd@@MAEHPAVCOleControlContainer@@PAPAVCOleControlSite@@IABU_GUID@@@Z:PROC ; CWnd::CreateControlSite
EXTRN	?Create@CDialog@@UAEHPB_WPAVCWnd@@@Z:PROC	; CDialog::Create
EXTRN	?Create@CDialog@@UAEHIPAVCWnd@@@Z:PROC		; CDialog::Create
EXTRN	?CreateIndirect@CDialog@@UAEHPBUDLGTEMPLATE@@PAVCWnd@@PAX@Z:PROC ; CDialog::CreateIndirect
EXTRN	?CreateIndirect@CDialog@@UAEHPAXPAVCWnd@@@Z:PROC ; CDialog::CreateIndirect
EXTRN	?DoModal@CDialog@@UAEHXZ:PROC			; CDialog::DoModal
EXTRN	?OnInitDialog@CDialog@@UAEHXZ:PROC		; CDialog::OnInitDialog
EXTRN	?OnSetFont@CDialog@@UAEXPAVCFont@@@Z:PROC	; CDialog::OnSetFont
EXTRN	?OnOK@CDialog@@MAEXXZ:PROC			; CDialog::OnOK
EXTRN	?OnCancel@CDialog@@MAEXXZ:PROC			; CDialog::OnCancel
EXTRN	??1CDialog@@UAE@XZ:PROC				; CDialog::~CDialog
EXTRN	?AssertValid@CDialog@@UBEXXZ:PROC		; CDialog::AssertValid
EXTRN	?Dump@CDialog@@UBEXAAVCDumpContext@@@Z:PROC	; CDialog::Dump
EXTRN	?OnCmdMsg@CDialog@@UAEHIHPAXPAUAFX_CMDHANDLERINFO@@@Z:PROC ; CDialog::OnCmdMsg
EXTRN	?CheckAutoCenter@CDialog@@UAEHXZ:PROC		; CDialog::CheckAutoCenter
EXTRN	?SetOccDialogInfo@CDialog@@MAEHPAU_AFX_OCC_DIALOG_INFO@@@Z:PROC ; CDialog::SetOccDialogInfo
EXTRN	?GetOccDialogInfo@CDialog@@MAEPAU_AFX_OCC_DIALOG_INFO@@XZ:PROC ; CDialog::GetOccDialogInfo
EXTRN	?PreInitDialog@CDialog@@MAEXXZ:PROC		; CDialog::PreInitDialog
EXTRN	?OnPaint@CDialog@@IAEXXZ:PROC			; CDialog::OnPaint
EXTRN	?AfxGetApp@@YGPAVCWinApp@@XZ:PROC		; AfxGetApp
EXTRN	?LoadIconW@CWinApp@@QBEPAUHICON__@@I@Z:PROC	; CWinApp::LoadIconW
EXTRN	??1CDialogImpl@@MAE@XZ:PROC			; CDialogImpl::~CDialogImpl
EXTRN	?GetRuntimeClass@CDialogEx@@UBEPAUCRuntimeClass@@XZ:PROC ; CDialogEx::GetRuntimeClass
EXTRN	??0CDialogEx@@QAE@IPAVCWnd@@@Z:PROC		; CDialogEx::CDialogEx
EXTRN	?PreTranslateMessage@CDialogEx@@UAEHPAUtagMSG@@@Z:PROC ; CDialogEx::PreTranslateMessage
EXTRN	?OnCommand@CDialogEx@@MAEHIJ@Z:PROC		; CDialogEx::OnCommand
EXTRN	??0Solution@@QAE@PAUHWND__@@@Z:PROC		; Solution::Solution
EXTRN	?Charger_valeur_saisie@Solution@@QAEHPAUHWND__@@@Z:PROC ; Solution::Charger_valeur_saisie
EXTRN	?Charger_From_a_File@Solution@@QAEHPAUHWND__@@@Z:PROC ; Solution::Charger_From_a_File
EXTRN	??_ECSUDOKUDlg@@UAEPAXI@Z:PROC			; CSUDOKUDlg::`vector deleting destructor'
EXTRN	@_RTC_CheckStackVars@8:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	___CxxFrameHandler3:PROC
EXTRN	_memset:PROC
EXTRN	??_7type_info@@6B@:QWORD			; type_info::`vftable'
EXTRN	___security_cookie:DWORD
;	COMDAT ?atlTraceException@ATL@@3V?$CTraceCategoryEx@$0CAAA@$0A@@1@A
_BSS	SEGMENT
?atlTraceException@ATL@@3V?$CTraceCategoryEx@$0CAAA@$0A@@1@A DD 01H DUP (?) ; ATL::atlTraceException
_BSS	ENDS
;	COMDAT ?atlTraceString@ATL@@3V?$CTraceCategoryEx@$0CAAAA@$0A@@1@A
_BSS	SEGMENT
?atlTraceString@ATL@@3V?$CTraceCategoryEx@$0CAAAA@$0A@@1@A DD 01H DUP (?) ; ATL::atlTraceString
_BSS	ENDS
;	COMDAT CRT$XCU
CRT$XCU	SEGMENT
_atlTraceException$initializer$ DD FLAT:??__EatlTraceException@ATL@@YAXXZ
CRT$XCU	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
rtc$IMZ	ENDS
;	COMDAT ??_R2CDialogEx@@8
rdata$r	SEGMENT
??_R2CDialogEx@@8 DD FLAT:??_R1A@?0A@EA@CDialogEx@@8	; CDialogEx::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@CDialog@@8
	DD	FLAT:??_R1A@?0A@EA@CWnd@@8
	DD	FLAT:??_R1A@?0A@EA@CCmdTarget@@8
	DD	FLAT:??_R1A@?0A@EA@CObject@@8
rdata$r	ENDS
;	COMDAT ??_R3CDialogEx@@8
rdata$r	SEGMENT
??_R3CDialogEx@@8 DD 00H				; CDialogEx::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	05H
	DD	FLAT:??_R2CDialogEx@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCDialogEx@@@8
data$r	SEGMENT
??_R0?AVCDialogEx@@@8 DD FLAT:??_7type_info@@6B@	; CDialogEx `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCDialogEx@@', 00H
data$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CDialogEx@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CDialogEx@@8 DD FLAT:??_R0?AVCDialogEx@@@8 ; CDialogEx::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	04H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CDialogEx@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CSUDOKUDlg@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CSUDOKUDlg@@8 DD FLAT:??_R0?AVCSUDOKUDlg@@@8 ; CSUDOKUDlg::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	05H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CSUDOKUDlg@@8
rdata$r	ENDS
;	COMDAT ??_R2CSUDOKUDlg@@8
rdata$r	SEGMENT
??_R2CSUDOKUDlg@@8 DD FLAT:??_R1A@?0A@EA@CSUDOKUDlg@@8	; CSUDOKUDlg::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@CDialogEx@@8
	DD	FLAT:??_R1A@?0A@EA@CDialog@@8
	DD	FLAT:??_R1A@?0A@EA@CWnd@@8
	DD	FLAT:??_R1A@?0A@EA@CCmdTarget@@8
	DD	FLAT:??_R1A@?0A@EA@CObject@@8
rdata$r	ENDS
;	COMDAT ??_R3CSUDOKUDlg@@8
rdata$r	SEGMENT
??_R3CSUDOKUDlg@@8 DD 00H				; CSUDOKUDlg::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	06H
	DD	FLAT:??_R2CSUDOKUDlg@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCSUDOKUDlg@@@8
data$r	SEGMENT
??_R0?AVCSUDOKUDlg@@@8 DD FLAT:??_7type_info@@6B@	; CSUDOKUDlg `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCSUDOKUDlg@@', 00H
data$r	ENDS
;	COMDAT ??_R4CSUDOKUDlg@@6B@
rdata$r	SEGMENT
??_R4CSUDOKUDlg@@6B@ DD 00H				; CSUDOKUDlg::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AVCSUDOKUDlg@@@8
	DD	FLAT:??_R3CSUDOKUDlg@@8
rdata$r	ENDS
;	COMDAT ?__LINE__Var@?1??OnBnClickedButton2@CSUDOKUDlg@@QAEXXZ@4JA
_DATA	SEGMENT
?__LINE__Var@?1??OnBnClickedButton2@CSUDOKUDlg@@QAEXXZ@4JA DD 091H ; `CSUDOKUDlg::OnBnClickedButton2'::`2'::__LINE__Var
_DATA	ENDS
;	COMDAT ??_C@_17IBCNDFFO@?$AAF?$AAi?$AAn?$AA?$AA@
CONST	SEGMENT
??_C@_17IBCNDFFO@?$AAF?$AAi?$AAn?$AA?$AA@ DB 'F', 00H, 'i', 00H, 'n', 00H
	DB	00H, 00H					; `string'
CONST	ENDS
;	COMDAT ??_C@_0CO@COLFEFNB@c?3?2projets?2sudoku?2sudoku?2sudoku?2@
CONST	SEGMENT
??_C@_0CO@COLFEFNB@c?3?2projets?2sudoku?2sudoku?2sudoku?2@ DB 'c:\projets'
	DB	'\sudoku\sudoku\sudoku\sudokudlg.cpp', 00H	; `string'
CONST	ENDS
;	COMDAT ?__LINE__Var@?1??OnBnClickedOk@CSUDOKUDlg@@QAEXXZ@4JA
_DATA	SEGMENT
?__LINE__Var@?1??OnBnClickedOk@CSUDOKUDlg@@QAEXXZ@4JA DD 060H ; `CSUDOKUDlg::OnBnClickedOk'::`2'::__LINE__Var
_DATA	ENDS
;	COMDAT ??_7CSUDOKUDlg@@6B@
CONST	SEGMENT
??_7CSUDOKUDlg@@6B@ DD FLAT:??_R4CSUDOKUDlg@@6B@	; CSUDOKUDlg::`vftable'
	DD	FLAT:?GetRuntimeClass@CDialogEx@@UBEPAUCRuntimeClass@@XZ
	DD	FLAT:??_ECSUDOKUDlg@@UAEPAXI@Z
	DD	FLAT:?Serialize@CObject@@UAEXAAVCArchive@@@Z
	DD	FLAT:?AssertValid@CDialog@@UBEXXZ
	DD	FLAT:?Dump@CDialog@@UBEXAAVCDumpContext@@@Z
	DD	FLAT:?OnCmdMsg@CDialog@@UAEHIHPAXPAUAFX_CMDHANDLERINFO@@@Z
	DD	FLAT:?OnFinalRelease@CWnd@@UAEXXZ
	DD	FLAT:?IsInvokeAllowed@CCmdTarget@@UAEHJ@Z
	DD	FLAT:?GetDispatchIID@CCmdTarget@@UAEHPAU_GUID@@@Z
	DD	FLAT:?GetTypeInfoCount@CCmdTarget@@UAEIXZ
	DD	FLAT:?GetTypeLibCache@CCmdTarget@@UAEPAVCTypeLibCache@@XZ
	DD	FLAT:?GetTypeLib@CCmdTarget@@UAEJKPAPAUITypeLib@@@Z
	DD	FLAT:?GetMessageMap@CSUDOKUDlg@@MBEPBUAFX_MSGMAP@@XZ
	DD	FLAT:?GetCommandMap@CCmdTarget@@MBEPBUAFX_OLECMDMAP@@XZ
	DD	FLAT:?GetDispatchMap@CCmdTarget@@MBEPBUAFX_DISPMAP@@XZ
	DD	FLAT:?GetConnectionMap@CCmdTarget@@MBEPBUAFX_CONNECTIONMAP@@XZ
	DD	FLAT:?GetInterfaceMap@CWnd@@MBEPBUAFX_INTERFACEMAP@@XZ
	DD	FLAT:?GetEventSinkMap@CCmdTarget@@MBEPBUAFX_EVENTSINKMAP@@XZ
	DD	FLAT:?OnCreateAggregates@CCmdTarget@@UAEHXZ
	DD	FLAT:?GetInterfaceHook@CCmdTarget@@UAEPAUIUnknown@@PBX@Z
	DD	FLAT:?GetExtraConnectionPoints@CCmdTarget@@MAEHPAVCPtrArray@@@Z
	DD	FLAT:?GetConnectionHook@CCmdTarget@@MAEPAUIConnectionPoint@@ABU_GUID@@@Z
	DD	FLAT:?PreSubclassWindow@CWnd@@UAEXXZ
	DD	FLAT:?Create@CWnd@@UAEHPB_W0KABUtagRECT@@PAV1@IPAUCCreateContext@@@Z
	DD	FLAT:?CreateEx@CWnd@@UAEHKPB_W0KABUtagRECT@@PAV1@IPAX@Z
	DD	FLAT:?CreateEx@CWnd@@UAEHKPB_W0KHHHHPAUHWND__@@PAUHMENU__@@PAX@Z
	DD	FLAT:?DestroyWindow@CWnd@@UAEHXZ
	DD	FLAT:?PreCreateWindow@CWnd@@UAEHAAUtagCREATESTRUCTW@@@Z
	DD	FLAT:?CalcWindowRect@CWnd@@UAEXPAUtagRECT@@I@Z
	DD	FLAT:?GetMenu@CWnd@@UBEPAVCMenu@@XZ
	DD	FLAT:?SetMenu@CWnd@@UAEHPAVCMenu@@@Z
	DD	FLAT:?OnToolHitTest@CWnd@@UBEHVCPoint@@PAUtagTOOLINFOW@@@Z
	DD	FLAT:?GetScrollBarCtrl@CWnd@@UBEPAVCScrollBar@@H@Z
	DD	FLAT:?WinHelpW@CWnd@@UAEXKI@Z
	DD	FLAT:?HtmlHelpW@CWnd@@UAEXKI@Z
	DD	FLAT:?WinHelpInternal@CWnd@@UAEXKI@Z
	DD	FLAT:?ContinueModal@CWnd@@UAEHXZ
	DD	FLAT:?EndModalLoop@CWnd@@UAEXH@Z
	DD	FLAT:?OnDrawIconicThumbnailOrLivePreview@CWnd@@UAEXAAVCDC@@VCRect@@VCSize@@HAAH@Z
	DD	FLAT:?EnsureStdObj@CWnd@@UAEJXZ
	DD	FLAT:?get_accParent@CWnd@@UAEJPAPAUIDispatch@@@Z
	DD	FLAT:?get_accChildCount@CWnd@@UAEJPAJ@Z
	DD	FLAT:?get_accChild@CWnd@@UAEJUtagVARIANT@@PAPAUIDispatch@@@Z
	DD	FLAT:?get_accName@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z
	DD	FLAT:?get_accValue@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z
	DD	FLAT:?get_accDescription@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z
	DD	FLAT:?get_accRole@CWnd@@UAEJUtagVARIANT@@PAU2@@Z
	DD	FLAT:?get_accState@CWnd@@UAEJUtagVARIANT@@PAU2@@Z
	DD	FLAT:?get_accHelp@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z
	DD	FLAT:?get_accHelpTopic@CWnd@@UAEJPAPA_WUtagVARIANT@@PAJ@Z
	DD	FLAT:?get_accKeyboardShortcut@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z
	DD	FLAT:?get_accFocus@CWnd@@UAEJPAUtagVARIANT@@@Z
	DD	FLAT:?get_accSelection@CWnd@@UAEJPAUtagVARIANT@@@Z
	DD	FLAT:?get_accDefaultAction@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z
	DD	FLAT:?accSelect@CWnd@@UAEJJUtagVARIANT@@@Z
	DD	FLAT:?accLocation@CWnd@@UAEJPAJ000UtagVARIANT@@@Z
	DD	FLAT:?accNavigate@CWnd@@UAEJJUtagVARIANT@@PAU2@@Z
	DD	FLAT:?accHitTest@CWnd@@UAEJJJPAUtagVARIANT@@@Z
	DD	FLAT:?accDoDefaultAction@CWnd@@UAEJUtagVARIANT@@@Z
	DD	FLAT:?put_accName@CWnd@@UAEJUtagVARIANT@@PA_W@Z
	DD	FLAT:?put_accValue@CWnd@@UAEJUtagVARIANT@@PA_W@Z
	DD	FLAT:?SetProxy@CWnd@@UAEJPAUIAccessibleProxy@@@Z
	DD	FLAT:?CreateAccessibleProxy@CWnd@@UAEJIJPAJ@Z
	DD	FLAT:?OnCommand@CDialogEx@@MAEHIJ@Z
	DD	FLAT:?OnNotify@CWnd@@MAEHIJPAJ@Z
	DD	FLAT:?GetSuperWndProcAddr@CWnd@@MAEPAP6GJPAUHWND__@@IIJ@ZXZ
	DD	FLAT:?DoDataExchange@CSUDOKUDlg@@MAEXPAVCDataExchange@@@Z
	DD	FLAT:?BeginModalState@CWnd@@UAEXXZ
	DD	FLAT:?EndModalState@CWnd@@UAEXXZ
	DD	FLAT:?PreTranslateMessage@CDialogEx@@UAEHPAUtagMSG@@@Z
	DD	FLAT:?OnAmbientProperty@CWnd@@UAEHPAVCOleControlSite@@JPAUtagVARIANT@@@Z
	DD	FLAT:?WindowProc@CWnd@@MAEJIIJ@Z
	DD	FLAT:?OnWndMsg@CWnd@@MAEHIIJPAJ@Z
	DD	FLAT:?DefWindowProcW@CWnd@@MAEJIIJ@Z
	DD	FLAT:?PostNcDestroy@CWnd@@MAEXXZ
	DD	FLAT:?OnChildNotify@CWnd@@MAEHIIJPAJ@Z
	DD	FLAT:?OnTouchInputs@CWnd@@MAEHIPAUtagTOUCHINPUT@@@Z
	DD	FLAT:?OnTouchInput@CWnd@@MAEHVCPoint@@HHPAUtagTOUCHINPUT@@@Z
	DD	FLAT:?GetGestureStatus@CWnd@@MAEKVCPoint@@@Z
	DD	FLAT:?OnGestureZoom@CWnd@@MAEHVCPoint@@J@Z
	DD	FLAT:?OnGesturePan@CWnd@@MAEHVCPoint@@0@Z
	DD	FLAT:?OnGestureRotate@CWnd@@MAEHVCPoint@@N@Z
	DD	FLAT:?OnGestureTwoFingerTap@CWnd@@MAEHVCPoint@@@Z
	DD	FLAT:?OnGesturePressAndTap@CWnd@@MAEHVCPoint@@J@Z
	DD	FLAT:?CheckAutoCenter@CDialog@@UAEHXZ
	DD	FLAT:?IsFrameWnd@CWnd@@UBEHXZ
	DD	FLAT:?CreateControlContainer@CWnd@@MAEHPAPAVCOleControlContainer@@@Z
	DD	FLAT:?CreateControlSite@CWnd@@MAEHPAVCOleControlContainer@@PAPAVCOleControlSite@@IABU_GUID@@@Z
	DD	FLAT:?SetOccDialogInfo@CDialog@@MAEHPAU_AFX_OCC_DIALOG_INFO@@@Z
	DD	FLAT:?GetOccDialogInfo@CDialog@@MAEPAU_AFX_OCC_DIALOG_INFO@@XZ
	DD	FLAT:?Create@CDialog@@UAEHIPAVCWnd@@@Z
	DD	FLAT:?Create@CDialog@@UAEHPB_WPAVCWnd@@@Z
	DD	FLAT:?CreateIndirect@CDialog@@UAEHPAXPAVCWnd@@@Z
	DD	FLAT:?CreateIndirect@CDialog@@UAEHPBUDLGTEMPLATE@@PAVCWnd@@PAX@Z
	DD	FLAT:?DoModal@CDialog@@UAEHXZ
	DD	FLAT:?OnInitDialog@CSUDOKUDlg@@MAEHXZ
	DD	FLAT:?OnSetFont@CDialog@@UAEXPAVCFont@@@Z
	DD	FLAT:?OnOK@CDialog@@MAEXXZ
	DD	FLAT:?OnCancel@CDialog@@MAEXXZ
	DD	FLAT:?PreInitDialog@CDialog@@MAEXXZ
CONST	ENDS
;	COMDAT ??_R2CCmdTarget@@8
rdata$r	SEGMENT
??_R2CCmdTarget@@8 DD FLAT:??_R1A@?0A@EA@CCmdTarget@@8	; CCmdTarget::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@CObject@@8
rdata$r	ENDS
;	COMDAT ??_R3CCmdTarget@@8
rdata$r	SEGMENT
??_R3CCmdTarget@@8 DD 00H				; CCmdTarget::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	FLAT:??_R2CCmdTarget@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCCmdTarget@@@8
data$r	SEGMENT
??_R0?AVCCmdTarget@@@8 DD FLAT:??_7type_info@@6B@	; CCmdTarget `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCCmdTarget@@', 00H
data$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CCmdTarget@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CCmdTarget@@8 DD FLAT:??_R0?AVCCmdTarget@@@8 ; CCmdTarget::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CCmdTarget@@8
rdata$r	ENDS
;	COMDAT ??_R2CWnd@@8
rdata$r	SEGMENT
??_R2CWnd@@8 DD	FLAT:??_R1A@?0A@EA@CWnd@@8		; CWnd::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@CCmdTarget@@8
	DD	FLAT:??_R1A@?0A@EA@CObject@@8
rdata$r	ENDS
;	COMDAT ??_R3CWnd@@8
rdata$r	SEGMENT
??_R3CWnd@@8 DD	00H					; CWnd::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	03H
	DD	FLAT:??_R2CWnd@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCWnd@@@8
data$r	SEGMENT
??_R0?AVCWnd@@@8 DD FLAT:??_7type_info@@6B@		; CWnd `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCWnd@@', 00H
data$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CWnd@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CWnd@@8 DD FLAT:??_R0?AVCWnd@@@8		; CWnd::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	02H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CWnd@@8
rdata$r	ENDS
;	COMDAT ??_R2CDialog@@8
rdata$r	SEGMENT
??_R2CDialog@@8 DD FLAT:??_R1A@?0A@EA@CDialog@@8	; CDialog::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@CWnd@@8
	DD	FLAT:??_R1A@?0A@EA@CCmdTarget@@8
	DD	FLAT:??_R1A@?0A@EA@CObject@@8
rdata$r	ENDS
;	COMDAT ??_R3CDialog@@8
rdata$r	SEGMENT
??_R3CDialog@@8 DD 00H					; CDialog::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	04H
	DD	FLAT:??_R2CDialog@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCDialog@@@8
data$r	SEGMENT
??_R0?AVCDialog@@@8 DD FLAT:??_7type_info@@6B@		; CDialog `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCDialog@@', 00H
data$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CDialog@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CDialog@@8 DD FLAT:??_R0?AVCDialog@@@8	; CDialog::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	03H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CDialog@@8
rdata$r	ENDS
;	COMDAT ??_R2CObject@@8
rdata$r	SEGMENT
??_R2CObject@@8 DD FLAT:??_R1A@?0A@EA@CObject@@8	; CObject::`RTTI Base Class Array'
rdata$r	ENDS
;	COMDAT ??_R3CObject@@8
rdata$r	SEGMENT
??_R3CObject@@8 DD 00H					; CObject::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	FLAT:??_R2CObject@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCObject@@@8
data$r	SEGMENT
??_R0?AVCObject@@@8 DD FLAT:??_7type_info@@6B@		; CObject `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCObject@@', 00H
data$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CObject@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CObject@@8 DD FLAT:??_R0?AVCObject@@@8	; CObject::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CObject@@8
rdata$r	ENDS
;	COMDAT ??_C@_11LOCGONAA@?$AA?$AA@
CONST	SEGMENT
??_C@_11LOCGONAA@?$AA?$AA@ DB 00H, 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_1KC@GEMPEEJK@?$AAc?$AA?3?$AA?2?$AAp?$AAr?$AAo?$AAg?$AAr?$AAa?$AAm?$AA?5?$AAf?$AAi?$AAl?$AAe?$AAs?$AA?5?$AA?$CI?$AAx?$AA8?$AA6?$AA?$CJ?$AA?2?$AAm?$AAi?$AAc?$AAr?$AAo?$AAs?$AAo?$AAf?$AAt@
CONST	SEGMENT
??_C@_1KC@GEMPEEJK@?$AAc?$AA?3?$AA?2?$AAp?$AAr?$AAo?$AAg?$AAr?$AAa?$AAm?$AA?5?$AAf?$AAi?$AAl?$AAe?$AAs?$AA?5?$AA?$CI?$AAx?$AA8?$AA6?$AA?$CJ?$AA?2?$AAm?$AAi?$AAc?$AAr?$AAo?$AAs?$AAo?$AAf?$AAt@ DB 'c'
	DB	00H, ':', 00H, '\', 00H, 'p', 00H, 'r', 00H, 'o', 00H, 'g', 00H
	DB	'r', 00H, 'a', 00H, 'm', 00H, ' ', 00H, 'f', 00H, 'i', 00H, 'l'
	DB	00H, 'e', 00H, 's', 00H, ' ', 00H, '(', 00H, 'x', 00H, '8', 00H
	DB	'6', 00H, ')', 00H, '\', 00H, 'm', 00H, 'i', 00H, 'c', 00H, 'r'
	DB	00H, 'o', 00H, 's', 00H, 'o', 00H, 'f', 00H, 't', 00H, ' ', 00H
	DB	'v', 00H, 'i', 00H, 's', 00H, 'u', 00H, 'a', 00H, 'l', 00H, ' '
	DB	00H, 's', 00H, 't', 00H, 'u', 00H, 'd', 00H, 'i', 00H, 'o', 00H
	DB	' ', 00H, '1', 00H, '2', 00H, '.', 00H, '0', 00H, '\', 00H, 'v'
	DB	00H, 'c', 00H, '\', 00H, 'a', 00H, 't', 00H, 'l', 00H, 'm', 00H
	DB	'f', 00H, 'c', 00H, '\', 00H, 'i', 00H, 'n', 00H, 'c', 00H, 'l'
	DB	00H, 'u', 00H, 'd', 00H, 'e', 00H, '\', 00H, 'a', 00H, 't', 00H
	DB	'l', 00H, 't', 00H, 'r', 00H, 'a', 00H, 'c', 00H, 'e', 00H, '.'
	DB	00H, 'h', 00H, 00H, 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_1EO@EBPPKGOM@?$AAf?$AAa?$AAl?$AAs?$AAe?$AA?5?$AA?$CG?$AA?$CG?$AA?5?$AA?$CC?$AAT?$AAo?$AAo?$AA?5?$AAm?$AAa?$AAn?$AAy?$AA?5?$AAc?$AAa?$AAt?$AAe?$AAg?$AAo?$AAr?$AAi?$AAe?$AAs?$AA?5?$AAd?$AAe@
CONST	SEGMENT
??_C@_1EO@EBPPKGOM@?$AAf?$AAa?$AAl?$AAs?$AAe?$AA?5?$AA?$CG?$AA?$CG?$AA?5?$AA?$CC?$AAT?$AAo?$AAo?$AA?5?$AAm?$AAa?$AAn?$AAy?$AA?5?$AAc?$AAa?$AAt?$AAe?$AAg?$AAo?$AAr?$AAi?$AAe?$AAs?$AA?5?$AAd?$AAe@ DB 'f'
	DB	00H, 'a', 00H, 'l', 00H, 's', 00H, 'e', 00H, ' ', 00H, '&', 00H
	DB	'&', 00H, ' ', 00H, '"', 00H, 'T', 00H, 'o', 00H, 'o', 00H, ' '
	DB	00H, 'm', 00H, 'a', 00H, 'n', 00H, 'y', 00H, ' ', 00H, 'c', 00H
	DB	'a', 00H, 't', 00H, 'e', 00H, 'g', 00H, 'o', 00H, 'r', 00H, 'i'
	DB	00H, 'e', 00H, 's', 00H, ' ', 00H, 'd', 00H, 'e', 00H, 'f', 00H
	DB	'i', 00H, 'n', 00H, 'e', 00H, 'd', 00H, '"', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_1BO@GMLILNDJ@?$AAa?$AAt?$AAl?$AAT?$AAr?$AAa?$AAc?$AAe?$AAS?$AAt?$AAr?$AAi?$AAn?$AAg?$AA?$AA@
CONST	SEGMENT
??_C@_1BO@GMLILNDJ@?$AAa?$AAt?$AAl?$AAT?$AAr?$AAa?$AAc?$AAe?$AAS?$AAt?$AAr?$AAi?$AAn?$AAg?$AA?$AA@ DB 'a'
	DB	00H, 't', 00H, 'l', 00H, 'T', 00H, 'r', 00H, 'a', 00H, 'c', 00H
	DB	'e', 00H, 'S', 00H, 't', 00H, 'r', 00H, 'i', 00H, 'n', 00H, 'g'
	DB	00H, 00H, 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_1CE@IMMADNAP@?$AAa?$AAt?$AAl?$AAT?$AAr?$AAa?$AAc?$AAe?$AAE?$AAx?$AAc?$AAe?$AAp?$AAt?$AAi?$AAo?$AAn?$AA?$AA@
CONST	SEGMENT
??_C@_1CE@IMMADNAP@?$AAa?$AAt?$AAl?$AAT?$AAr?$AAa?$AAc?$AAe?$AAE?$AAx?$AAc?$AAe?$AAp?$AAt?$AAi?$AAo?$AAn?$AA?$AA@ DB 'a'
	DB	00H, 't', 00H, 'l', 00H, 'T', 00H, 'r', 00H, 'a', 00H, 'c', 00H
	DB	'e', 00H, 'E', 00H, 'x', 00H, 'c', 00H, 'e', 00H, 'p', 00H, 't'
	DB	00H, 'i', 00H, 'o', 00H, 'n', 00H, 00H, 00H	; `string'
CONST	ENDS
;	COMDAT ??_C@_15GANGMFKL@?$AA?$CF?$AAs?$AA?$AA@
CONST	SEGMENT
??_C@_15GANGMFKL@?$AA?$CF?$AAs?$AA?$AA@ DB '%', 00H, 's', 00H, 00H, 00H ; `string'
CONST	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__unwindtable$?OnBnClickedButton2@CSUDOKUDlg@@QAEXXZ DD 0ffffffffH
	DD	FLAT:__unwindfunclet$?OnBnClickedButton2@CSUDOKUDlg@@QAEXXZ$0
	DD	00H
	DD	FLAT:__unwindfunclet$?OnBnClickedButton2@CSUDOKUDlg@@QAEXXZ$1
__ehfuncinfo$?OnBnClickedButton2@CSUDOKUDlg@@QAEXXZ DD 019930522H
	DD	02H
	DD	FLAT:__unwindtable$?OnBnClickedButton2@CSUDOKUDlg@@QAEXXZ
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__unwindtable$?OnBnClickedButton1@CSUDOKUDlg@@QAEXXZ DD 0ffffffffH
	DD	FLAT:__unwindfunclet$?OnBnClickedButton1@CSUDOKUDlg@@QAEXXZ$0
__ehfuncinfo$?OnBnClickedButton1@CSUDOKUDlg@@QAEXXZ DD 019930522H
	DD	01H
	DD	FLAT:__unwindtable$?OnBnClickedButton1@CSUDOKUDlg@@QAEXXZ
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__unwindtable$?OnBnClickedOk@CSUDOKUDlg@@QAEXXZ DD 0ffffffffH
	DD	FLAT:__unwindfunclet$?OnBnClickedOk@CSUDOKUDlg@@QAEXXZ$0
__ehfuncinfo$?OnBnClickedOk@CSUDOKUDlg@@QAEXXZ DD 019930522H
	DD	01H
	DD	FLAT:__unwindtable$?OnBnClickedOk@CSUDOKUDlg@@QAEXXZ
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__unwindtable$?OnPaint@CSUDOKUDlg@@IAEXXZ DD 0ffffffffH
	DD	FLAT:__unwindfunclet$?OnPaint@CSUDOKUDlg@@IAEXXZ$0
__ehfuncinfo$?OnPaint@CSUDOKUDlg@@IAEXXZ DD 019930522H
	DD	01H
	DD	FLAT:__unwindtable$?OnPaint@CSUDOKUDlg@@IAEXXZ
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__unwindtable$??0CSUDOKUDlg@@QAE@PAVCWnd@@@Z DD 0ffffffffH
	DD	FLAT:__unwindfunclet$??0CSUDOKUDlg@@QAE@PAVCWnd@@@Z$0
__ehfuncinfo$??0CSUDOKUDlg@@QAE@PAVCWnd@@@Z DD 019930522H
	DD	01H
	DD	FLAT:__unwindtable$??0CSUDOKUDlg@@QAE@PAVCWnd@@@Z
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
xdata$x	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__unwindtable$??1CDialogEx@@UAE@XZ DD 0ffffffffH
	DD	FLAT:__unwindfunclet$??1CDialogEx@@UAE@XZ$0
	DD	00H
	DD	FLAT:__unwindfunclet$??1CDialogEx@@UAE@XZ$1
__ehfuncinfo$??1CDialogEx@@UAE@XZ DD 019930522H
	DD	02H
	DD	FLAT:__unwindtable$??1CDialogEx@@UAE@XZ
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
xdata$x	ENDS
;	COMDAT CRT$XCU
CRT$XCU	SEGMENT
_atlTraceString$initializer$ DD FLAT:??__EatlTraceString@ATL@@YAXXZ
CRT$XCU	ENDS
; Function compile flags: /Odsp /RTCsu /ZI
;	COMDAT ??_GCSUDOKUDlg@@UAEPAXI@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
___flags$ = 8						; size = 4
??_GCSUDOKUDlg@@UAEPAXI@Z PROC				; CSUDOKUDlg::`scalar deleting destructor', COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	push	51					; 00000033H
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??1CSUDOKUDlg@@UAE@XZ
	mov	eax, DWORD PTR ___flags$[ebp]
	and	eax, 1
	je	SHORT $LN1@scalar
	push	DWORD PTR _this$[ebp]
	call	??3CObject@@SGXPAX@Z			; CObject::operator delete
$LN1@scalar:
	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??_GCSUDOKUDlg@@UAEPAXI@Z ENDP				; CSUDOKUDlg::`scalar deleting destructor'
_TEXT	ENDS
; Function compile flags: /Odsp /RTCsu /ZI
;	COMDAT ??1CSUDOKUDlg@@UAE@XZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
??1CSUDOKUDlg@@UAE@XZ PROC				; CSUDOKUDlg::~CSUDOKUDlg, COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	push	51					; 00000033H
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??1CDialogEx@@UAE@XZ
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
??1CSUDOKUDlg@@UAE@XZ ENDP				; CSUDOKUDlg::~CSUDOKUDlg
_TEXT	ENDS
; Function compile flags: /Odsp /RTCsu /ZI
; File c:\projets\sudoku\sudoku\sudoku\sudokudlg.cpp
;	COMDAT ?OnBnClickedButton2@CSUDOKUDlg@@QAEXXZ
_TEXT	SEGMENT
tv186 = -320						; size = 4
tv88 = -320						; size = 4
$T2 = -312						; size = 4
$T3 = -300						; size = 4
$T4 = -288						; size = 4
$T5 = -276						; size = 4
_col$6 = -72						; size = 4
_row$7 = -60						; size = 4
_z$ = -48						; size = 4
_Chaine$ = -36						; size = 4
_this$ = -24						; size = 4
__$ArrayPad$ = -16					; size = 4
__$EHRec$ = -12						; size = 12
?OnBnClickedButton2@CSUDOKUDlg@@QAEXXZ PROC		; CSUDOKUDlg::OnBnClickedButton2, COMDAT
; _this$ = ecx

; 145  : {

	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?OnBnClickedButton2@CSUDOKUDlg@@QAEXXZ
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 308				; 00000134H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-320]
	push	77					; 0000004dH
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR _this$[ebp], ecx

; 146  : 	// TODO: ajoutez ici le code de votre gestionnaire de notification de contrôle
; 147  : 
; 148  : 	CString Chaine(_T(""));

	mov	esi, esp
	push	OFFSET ??_C@_11LOCGONAA@?$AA?$AA@
	lea	ecx, DWORD PTR _Chaine$[ebp]
	call	DWORD PTR __imp_??0?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@PB_W@Z
	cmp	esi, esp
	call	__RTC_CheckEsp
	and	DWORD PTR __$EHRec$[ebp+8], 0

; 149  : 	int z = 0;

	and	DWORD PTR _z$[ebp], 0

; 150  : 
; 151  : 	pt_solution = new Solution(m_hWnd);

	mov	eax, DWORD PTR ?__LINE__Var@?1??OnBnClickedButton2@CSUDOKUDlg@@QAEXXZ@4JA
	add	eax, 6
	push	eax
	push	OFFSET ??_C@_0CO@COLFEFNB@c?3?2projets?2sudoku?2sudoku?2sudoku?2@
	push	676					; 000002a4H
	call	??2@YAPAXIPBDH@Z			; operator new
	add	esp, 12					; 0000000cH
	mov	DWORD PTR $T3[ebp], eax
	mov	BYTE PTR __$EHRec$[ebp+8], 1
	cmp	DWORD PTR $T3[ebp], 0
	je	SHORT $LN11@OnBnClicke
	mov	eax, DWORD PTR _this$[ebp]
	push	DWORD PTR [eax+32]
	mov	ecx, DWORD PTR $T3[ebp]
	call	??0Solution@@QAE@PAUHWND__@@@Z		; Solution::Solution
	mov	DWORD PTR tv88[ebp], eax
	jmp	SHORT $LN12@OnBnClicke
$LN11@OnBnClicke:
	and	DWORD PTR tv88[ebp], 0
$LN12@OnBnClicke:
	mov	eax, DWORD PTR tv88[ebp]
	mov	DWORD PTR $T2[ebp], eax
	mov	BYTE PTR __$EHRec$[ebp+8], 0
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR $T2[ebp]
	mov	DWORD PTR [eax+192], ecx

; 152  : 
; 153  : 
; 154  : 
; 155  : 	for (int row = 0; row < MAX; row++)

	and	DWORD PTR _row$7[ebp], 0
	jmp	SHORT $LN8@OnBnClicke
$LN7@OnBnClicke:
	mov	eax, DWORD PTR _row$7[ebp]
	inc	eax
	mov	DWORD PTR _row$7[ebp], eax
$LN8@OnBnClicke:
	cmp	DWORD PTR _row$7[ebp], 9
	jge	SHORT $LN6@OnBnClicke

; 156  : 	{
; 157  : 		for (int col = 0; col < MAX; col++)

	and	DWORD PTR _col$6[ebp], 0
	jmp	SHORT $LN5@OnBnClicke
$LN4@OnBnClicke:
	mov	eax, DWORD PTR _col$6[ebp]
	inc	eax
	mov	DWORD PTR _col$6[ebp], eax
$LN5@OnBnClicke:
	cmp	DWORD PTR _col$6[ebp], 9
	jge	SHORT $LN3@OnBnClicke

; 158  : 		{
; 159  : 			::SetDlgItemTextW(m_hWnd, (IDC_EDIT1 + z), (LPWSTR)Chaine.GetBuffer());

	mov	esi, esp
	lea	ecx, DWORD PTR _Chaine$[ebp]
	call	DWORD PTR __imp_?GetBuffer@?$CSimpleStringT@_W$00@ATL@@QAEPA_WXZ
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	esi, esp
	push	eax
	mov	eax, DWORD PTR _z$[ebp]
	add	eax, 1000				; 000003e8H
	push	eax
	mov	eax, DWORD PTR _this$[ebp]
	push	DWORD PTR [eax+32]
	call	DWORD PTR __imp__SetDlgItemTextW@12
	cmp	esi, esp
	call	__RTC_CheckEsp

; 160  : 			z++;

	mov	eax, DWORD PTR _z$[ebp]
	inc	eax
	mov	DWORD PTR _z$[ebp], eax

; 161  : 		}

	jmp	SHORT $LN4@OnBnClicke
$LN3@OnBnClicke:

; 162  : 	}

	jmp	SHORT $LN7@OnBnClicke
$LN6@OnBnClicke:

; 163  : 
; 164  : 	if (pt_solution->Charger_From_a_File(m_hWnd) == TRUE)

	mov	eax, DWORD PTR _this$[ebp]
	push	DWORD PTR [eax+32]
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+192]
	call	?Charger_From_a_File@Solution@@QAEHPAUHWND__@@@Z ; Solution::Charger_From_a_File
	cmp	eax, 1
	jne	SHORT $LN2@OnBnClicke

; 165  : 	{
; 166  : 		GetDlgItem(IDOK)->EnableWindow(TRUE);

	push	1
	push	1
	mov	ecx, DWORD PTR _this$[ebp]
	call	?GetDlgItem@CWnd@@QBEPAV1@H@Z		; CWnd::GetDlgItem
	mov	ecx, eax
	call	?EnableWindow@CWnd@@QAEHH@Z		; CWnd::EnableWindow

; 167  : 		GetDlgItem(IDCANCEL)->SetWindowTextW(_T("Fin"));

	push	OFFSET ??_C@_17IBCNDFFO@?$AAF?$AAi?$AAn?$AA?$AA@
	push	2
	mov	ecx, DWORD PTR _this$[ebp]
	call	?GetDlgItem@CWnd@@QBEPAV1@H@Z		; CWnd::GetDlgItem
	mov	ecx, eax
	call	?SetWindowTextW@CWnd@@QAEXPB_W@Z	; CWnd::SetWindowTextW

; 168  : 		GetDlgItem(IDC_BUTTON1)->EnableWindow(TRUE);

	push	1
	push	1081					; 00000439H
	mov	ecx, DWORD PTR _this$[ebp]
	call	?GetDlgItem@CWnd@@QBEPAV1@H@Z		; CWnd::GetDlgItem
	mov	ecx, eax
	call	?EnableWindow@CWnd@@QAEHH@Z		; CWnd::EnableWindow
$LN2@OnBnClicke:

; 169  : 	}
; 170  : 
; 171  : 	if (pt_solution != 0)

	mov	eax, DWORD PTR _this$[ebp]
	cmp	DWORD PTR [eax+192], 0
	je	SHORT $LN1@OnBnClicke

; 172  : 	{
; 173  : 		delete pt_solution;

	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+192]
	mov	DWORD PTR $T5[ebp], eax
	mov	eax, DWORD PTR $T5[ebp]
	mov	DWORD PTR $T4[ebp], eax
	cmp	DWORD PTR $T4[ebp], 0
	je	SHORT $LN13@OnBnClicke
	mov	esi, esp
	push	1
	mov	eax, DWORD PTR $T4[ebp]
	mov	eax, DWORD PTR [eax]
	mov	ecx, DWORD PTR $T4[ebp]
	call	DWORD PTR [eax]
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR tv186[ebp], eax
	jmp	SHORT $LN1@OnBnClicke
$LN13@OnBnClicke:
	and	DWORD PTR tv186[ebp], 0
$LN1@OnBnClicke:

; 174  : 	}
; 175  : }

	or	DWORD PTR __$EHRec$[ebp+8], -1
	mov	esi, esp
	lea	ecx, DWORD PTR _Chaine$[ebp]
	call	DWORD PTR __imp_??1?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ
	cmp	esi, esp
	call	__RTC_CheckEsp
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN20@OnBnClicke
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 320				; 00000140H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	1
$LN20@OnBnClicke:
	DD	1
	DD	$LN19@OnBnClicke
$LN19@OnBnClicke:
	DD	-36					; ffffffdcH
	DD	4
	DD	$LN17@OnBnClicke
$LN17@OnBnClicke:
	DB	67					; 00000043H
	DB	104					; 00000068H
	DB	97					; 00000061H
	DB	105					; 00000069H
	DB	110					; 0000006eH
	DB	101					; 00000065H
	DB	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$?OnBnClickedButton2@CSUDOKUDlg@@QAEXXZ$0:
	mov	esi, esp
	lea	ecx, DWORD PTR _Chaine$[ebp]
	call	DWORD PTR __imp_??1?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ
	cmp	esi, esp
	jmp	__RTC_CheckEsp
__unwindfunclet$?OnBnClickedButton2@CSUDOKUDlg@@QAEXXZ$1:
	mov	eax, DWORD PTR ?__LINE__Var@?1??OnBnClickedButton2@CSUDOKUDlg@@QAEXXZ@4JA
	add	eax, 6
	push	eax
	push	OFFSET ??_C@_0CO@COLFEFNB@c?3?2projets?2sudoku?2sudoku?2sudoku?2@
	push	DWORD PTR $T3[ebp]
	call	??3@YAXPAXPBDH@Z			; operator delete
	add	esp, 12					; 0000000cH
	ret	0
__ehhandler$?OnBnClickedButton2@CSUDOKUDlg@@QAEXXZ:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-324]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	ecx, DWORD PTR [edx-4]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$?OnBnClickedButton2@CSUDOKUDlg@@QAEXXZ
	jmp	___CxxFrameHandler3
text$x	ENDS
?OnBnClickedButton2@CSUDOKUDlg@@QAEXXZ ENDP		; CSUDOKUDlg::OnBnClickedButton2
; Function compile flags: /Odsp /RTCsu /ZI
; File c:\projets\sudoku\sudoku\sudoku\sudokudlg.cpp
;	COMDAT ?OnBnClickedButton1@CSUDOKUDlg@@QAEXXZ
_TEXT	SEGMENT
_col$2 = -72						; size = 4
_row$3 = -60						; size = 4
_Chaine$ = -48						; size = 4
_z$ = -36						; size = 4
_this$ = -24						; size = 4
__$ArrayPad$ = -16					; size = 4
__$EHRec$ = -12						; size = 12
?OnBnClickedButton1@CSUDOKUDlg@@QAEXXZ PROC		; CSUDOKUDlg::OnBnClickedButton1, COMDAT
; _this$ = ecx

; 123  : {

	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?OnBnClickedButton1@CSUDOKUDlg@@QAEXXZ
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 256				; 00000100H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-268]
	push	64					; 00000040H
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR _this$[ebp], ecx

; 124  : 	// TODO: ajoutez ici le code de votre gestionnaire de notification de contrôle
; 125  : 
; 126  : 	int z = 0;

	and	DWORD PTR _z$[ebp], 0

; 127  : 	CString Chaine(_T(""));

	mov	esi, esp
	push	OFFSET ??_C@_11LOCGONAA@?$AA?$AA@
	lea	ecx, DWORD PTR _Chaine$[ebp]
	call	DWORD PTR __imp_??0?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@PB_W@Z
	cmp	esi, esp
	call	__RTC_CheckEsp
	and	DWORD PTR __$EHRec$[ebp+8], 0

; 128  : 
; 129  : 	for (int row = 0; row < MAX; row++)

	and	DWORD PTR _row$3[ebp], 0
	jmp	SHORT $LN6@OnBnClicke
$LN5@OnBnClicke:
	mov	eax, DWORD PTR _row$3[ebp]
	inc	eax
	mov	DWORD PTR _row$3[ebp], eax
$LN6@OnBnClicke:
	cmp	DWORD PTR _row$3[ebp], 9
	jge	SHORT $LN4@OnBnClicke

; 130  : 	{
; 131  : 		for (int col = 0; col < MAX; col++)

	and	DWORD PTR _col$2[ebp], 0
	jmp	SHORT $LN3@OnBnClicke
$LN2@OnBnClicke:
	mov	eax, DWORD PTR _col$2[ebp]
	inc	eax
	mov	DWORD PTR _col$2[ebp], eax
$LN3@OnBnClicke:
	cmp	DWORD PTR _col$2[ebp], 9
	jge	SHORT $LN1@OnBnClicke

; 132  : 		{
; 133  : 			::SetDlgItemTextW(m_hWnd, (IDC_EDIT1 + z), (LPWSTR)Chaine.GetBuffer());

	mov	esi, esp
	lea	ecx, DWORD PTR _Chaine$[ebp]
	call	DWORD PTR __imp_?GetBuffer@?$CSimpleStringT@_W$00@ATL@@QAEPA_WXZ
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	esi, esp
	push	eax
	mov	eax, DWORD PTR _z$[ebp]
	add	eax, 1000				; 000003e8H
	push	eax
	mov	eax, DWORD PTR _this$[ebp]
	push	DWORD PTR [eax+32]
	call	DWORD PTR __imp__SetDlgItemTextW@12
	cmp	esi, esp
	call	__RTC_CheckEsp

; 134  : 			z++;

	mov	eax, DWORD PTR _z$[ebp]
	inc	eax
	mov	DWORD PTR _z$[ebp], eax

; 135  : 		}

	jmp	SHORT $LN2@OnBnClicke
$LN1@OnBnClicke:

; 136  : 	}

	jmp	SHORT $LN5@OnBnClicke
$LN4@OnBnClicke:

; 137  : 
; 138  : 	GetDlgItem(IDOK)->EnableWindow(TRUE);

	push	1
	push	1
	mov	ecx, DWORD PTR _this$[ebp]
	call	?GetDlgItem@CWnd@@QBEPAV1@H@Z		; CWnd::GetDlgItem
	mov	ecx, eax
	call	?EnableWindow@CWnd@@QAEHH@Z		; CWnd::EnableWindow

; 139  : 	::SetDlgItemTextW(m_hWnd, IDC_STATIC, _T(""));

	mov	esi, esp
	push	OFFSET ??_C@_11LOCGONAA@?$AA?$AA@
	push	-1
	mov	eax, DWORD PTR _this$[ebp]
	push	DWORD PTR [eax+32]
	call	DWORD PTR __imp__SetDlgItemTextW@12
	cmp	esi, esp
	call	__RTC_CheckEsp

; 140  : 
; 141  : }

	or	DWORD PTR __$EHRec$[ebp+8], -1
	mov	esi, esp
	lea	ecx, DWORD PTR _Chaine$[ebp]
	call	DWORD PTR __imp_??1?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ
	cmp	esi, esp
	call	__RTC_CheckEsp
	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN13@OnBnClicke
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 268				; 0000010cH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	1
$LN13@OnBnClicke:
	DD	1
	DD	$LN12@OnBnClicke
$LN12@OnBnClicke:
	DD	-48					; ffffffd0H
	DD	4
	DD	$LN10@OnBnClicke
$LN10@OnBnClicke:
	DB	67					; 00000043H
	DB	104					; 00000068H
	DB	97					; 00000061H
	DB	105					; 00000069H
	DB	110					; 0000006eH
	DB	101					; 00000065H
	DB	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$?OnBnClickedButton1@CSUDOKUDlg@@QAEXXZ$0:
	mov	esi, esp
	lea	ecx, DWORD PTR _Chaine$[ebp]
	call	DWORD PTR __imp_??1?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ
	cmp	esi, esp
	jmp	__RTC_CheckEsp
__ehhandler$?OnBnClickedButton1@CSUDOKUDlg@@QAEXXZ:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-272]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	ecx, DWORD PTR [edx-4]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$?OnBnClickedButton1@CSUDOKUDlg@@QAEXXZ
	jmp	___CxxFrameHandler3
text$x	ENDS
?OnBnClickedButton1@CSUDOKUDlg@@QAEXXZ ENDP		; CSUDOKUDlg::OnBnClickedButton1
; Function compile flags: /Odsp /RTCsu /ZI
; File c:\projets\sudoku\sudoku\sudoku\sudokudlg.cpp
;	COMDAT ?OnBnClickedCancel@CSUDOKUDlg@@QAEXXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?OnBnClickedCancel@CSUDOKUDlg@@QAEXXZ PROC		; CSUDOKUDlg::OnBnClickedCancel, COMDAT
; _this$ = ecx

; 115  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	push	51					; 00000033H
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 116  : 	// TODO: ajoutez ici le code de votre gestionnaire de notification de contrôle
; 117  : 
; 118  : 	CDialogEx::OnCancel();

	mov	ecx, DWORD PTR _this$[ebp]
	call	?OnCancel@CDialog@@MAEXXZ		; CDialog::OnCancel

; 119  : }

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?OnBnClickedCancel@CSUDOKUDlg@@QAEXXZ ENDP		; CSUDOKUDlg::OnBnClickedCancel
_TEXT	ENDS
; Function compile flags: /Odsp /RTCsu /ZI
; File c:\projets\sudoku\sudoku\sudoku\sudokudlg.cpp
;	COMDAT ?OnBnClickedOk@CSUDOKUDlg@@QAEXXZ
_TEXT	SEGMENT
tv162 = -268						; size = 4
tv84 = -268						; size = 4
$T2 = -260						; size = 4
$T3 = -248						; size = 4
$T4 = -236						; size = 4
$T5 = -224						; size = 4
_this$ = -20						; size = 4
__$EHRec$ = -12						; size = 12
?OnBnClickedOk@CSUDOKUDlg@@QAEXXZ PROC			; CSUDOKUDlg::OnBnClickedOk, COMDAT
; _this$ = ecx

; 96   : {

	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?OnBnClickedOk@CSUDOKUDlg@@QAEXXZ
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 256				; 00000100H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-268]
	push	64					; 00000040H
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR _this$[ebp], ecx

; 97   : 	// TODO: ajoutez ici le code de votre gestionnaire de notification de contrôle
; 98   : 	 pt_solution = new Solution(m_hWnd);

	mov	eax, DWORD PTR ?__LINE__Var@?1??OnBnClickedOk@CSUDOKUDlg@@QAEXXZ@4JA
	inc	eax
	inc	eax
	push	eax
	push	OFFSET ??_C@_0CO@COLFEFNB@c?3?2projets?2sudoku?2sudoku?2sudoku?2@
	push	676					; 000002a4H
	call	??2@YAPAXIPBDH@Z			; operator new
	add	esp, 12					; 0000000cH
	mov	DWORD PTR $T3[ebp], eax
	and	DWORD PTR __$EHRec$[ebp+8], 0
	cmp	DWORD PTR $T3[ebp], 0
	je	SHORT $LN5@OnBnClicke
	mov	eax, DWORD PTR _this$[ebp]
	push	DWORD PTR [eax+32]
	mov	ecx, DWORD PTR $T3[ebp]
	call	??0Solution@@QAE@PAUHWND__@@@Z		; Solution::Solution
	mov	DWORD PTR tv84[ebp], eax
	jmp	SHORT $LN6@OnBnClicke
$LN5@OnBnClicke:
	and	DWORD PTR tv84[ebp], 0
$LN6@OnBnClicke:
	mov	eax, DWORD PTR tv84[ebp]
	mov	DWORD PTR $T2[ebp], eax
	or	DWORD PTR __$EHRec$[ebp+8], -1
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR $T2[ebp]
	mov	DWORD PTR [eax+192], ecx

; 99   : 
; 100  : 	if (pt_solution->Charger_valeur_saisie(m_hWnd) == TRUE)

	mov	eax, DWORD PTR _this$[ebp]
	push	DWORD PTR [eax+32]
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR [eax+192]
	call	?Charger_valeur_saisie@Solution@@QAEHPAUHWND__@@@Z ; Solution::Charger_valeur_saisie
	cmp	eax, 1
	jne	SHORT $LN2@OnBnClicke

; 101  : 	{
; 102  : 		GetDlgItem(IDOK)->EnableWindow(FALSE);

	push	0
	push	1
	mov	ecx, DWORD PTR _this$[ebp]
	call	?GetDlgItem@CWnd@@QBEPAV1@H@Z		; CWnd::GetDlgItem
	mov	ecx, eax
	call	?EnableWindow@CWnd@@QAEHH@Z		; CWnd::EnableWindow

; 103  : 		GetDlgItem(IDCANCEL)->SetWindowTextW(_T("Fin"));

	push	OFFSET ??_C@_17IBCNDFFO@?$AAF?$AAi?$AAn?$AA?$AA@
	push	2
	mov	ecx, DWORD PTR _this$[ebp]
	call	?GetDlgItem@CWnd@@QBEPAV1@H@Z		; CWnd::GetDlgItem
	mov	ecx, eax
	call	?SetWindowTextW@CWnd@@QAEXPB_W@Z	; CWnd::SetWindowTextW

; 104  : 		GetDlgItem(IDC_BUTTON1)->EnableWindow(TRUE);

	push	1
	push	1081					; 00000439H
	mov	ecx, DWORD PTR _this$[ebp]
	call	?GetDlgItem@CWnd@@QBEPAV1@H@Z		; CWnd::GetDlgItem
	mov	ecx, eax
	call	?EnableWindow@CWnd@@QAEHH@Z		; CWnd::EnableWindow
$LN2@OnBnClicke:

; 105  : 	}
; 106  : 	
; 107  : 	if (pt_solution != 0)

	mov	eax, DWORD PTR _this$[ebp]
	cmp	DWORD PTR [eax+192], 0
	je	SHORT $LN3@OnBnClicke

; 108  : 	{
; 109  : 		delete pt_solution;

	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+192]
	mov	DWORD PTR $T5[ebp], eax
	mov	eax, DWORD PTR $T5[ebp]
	mov	DWORD PTR $T4[ebp], eax
	cmp	DWORD PTR $T4[ebp], 0
	je	SHORT $LN7@OnBnClicke
	mov	esi, esp
	push	1
	mov	eax, DWORD PTR $T4[ebp]
	mov	eax, DWORD PTR [eax]
	mov	ecx, DWORD PTR $T4[ebp]
	call	DWORD PTR [eax]
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR tv162[ebp], eax
	jmp	SHORT $LN3@OnBnClicke
$LN7@OnBnClicke:
	and	DWORD PTR tv162[ebp], 0
$LN3@OnBnClicke:

; 110  : 	}
; 111  : }

	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 268				; 0000010cH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$?OnBnClickedOk@CSUDOKUDlg@@QAEXXZ$0:
	mov	eax, DWORD PTR ?__LINE__Var@?1??OnBnClickedOk@CSUDOKUDlg@@QAEXXZ@4JA
	inc	eax
	inc	eax
	push	eax
	push	OFFSET ??_C@_0CO@COLFEFNB@c?3?2projets?2sudoku?2sudoku?2sudoku?2@
	push	DWORD PTR $T3[ebp]
	call	??3@YAXPAXPBDH@Z			; operator delete
	add	esp, 12					; 0000000cH
	ret	0
__ehhandler$?OnBnClickedOk@CSUDOKUDlg@@QAEXXZ:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-272]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$?OnBnClickedOk@CSUDOKUDlg@@QAEXXZ
	jmp	___CxxFrameHandler3
text$x	ENDS
?OnBnClickedOk@CSUDOKUDlg@@QAEXXZ ENDP			; CSUDOKUDlg::OnBnClickedOk
; Function compile flags: /Odsp /RTCsu /ZI
; File c:\projets\sudoku\sudoku\sudoku\sudokudlg.cpp
;	COMDAT ?GetMessageMap@CSUDOKUDlg@@MBEPBUAFX_MSGMAP@@XZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?GetMessageMap@CSUDOKUDlg@@MBEPBUAFX_MSGMAP@@XZ PROC	; CSUDOKUDlg::GetMessageMap, COMDAT
; _this$ = ecx

; 29   : BEGIN_MESSAGE_MAP(CSUDOKUDlg, CDialogEx)

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	push	51					; 00000033H
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	call	?GetThisMessageMap@CSUDOKUDlg@@KGPBUAFX_MSGMAP@@XZ ; CSUDOKUDlg::GetThisMessageMap
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?GetMessageMap@CSUDOKUDlg@@MBEPBUAFX_MSGMAP@@XZ ENDP	; CSUDOKUDlg::GetMessageMap
_TEXT	ENDS
; Function compile flags: /Odsp /RTCsu /ZI
; File c:\projets\sudoku\sudoku\sudoku\sudokudlg.cpp
;	COMDAT ?GetThisMessageMap@CSUDOKUDlg@@KGPBUAFX_MSGMAP@@XZ
_TEXT	SEGMENT
?GetThisMessageMap@CSUDOKUDlg@@KGPBUAFX_MSGMAP@@XZ PROC	; CSUDOKUDlg::GetThisMessageMap, COMDAT

; 29   : BEGIN_MESSAGE_MAP(CSUDOKUDlg, CDialogEx)

	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	push	48					; 00000030H
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd

; 30   : 	ON_WM_PAINT()
; 31   : 	ON_WM_QUERYDRAGICON()
; 32   : 	ON_BN_CLICKED(IDOK, &CSUDOKUDlg::OnBnClickedOk)
; 33   : 	ON_BN_CLICKED(IDCANCEL, &CSUDOKUDlg::OnBnClickedCancel)
; 34   : 	ON_BN_CLICKED(IDC_BUTTON1, &CSUDOKUDlg::OnBnClickedButton1)
; 35   : 	ON_BN_CLICKED(IDC_BUTTON2, &CSUDOKUDlg::OnBnClickedButton2)
; 36   : END_MESSAGE_MAP()

	mov	eax, OFFSET ?messageMap@?1??GetThisMessageMap@CSUDOKUDlg@@KGPBUAFX_MSGMAP@@XZ@4U3@B
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?GetThisMessageMap@CSUDOKUDlg@@KGPBUAFX_MSGMAP@@XZ ENDP	; CSUDOKUDlg::GetThisMessageMap
_TEXT	ENDS
; Function compile flags: /Odsp /RTCsu /ZI
; File c:\projets\sudoku\sudoku\sudoku\sudokudlg.cpp
;	COMDAT ?OnQueryDragIcon@CSUDOKUDlg@@IAEPAUHICON__@@XZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?OnQueryDragIcon@CSUDOKUDlg@@IAEPAUHICON__@@XZ PROC	; CSUDOKUDlg::OnQueryDragIcon, COMDAT
; _this$ = ecx

; 89   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	push	51					; 00000033H
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 90   : 	return static_cast<HCURSOR>(m_hIcon);

	mov	eax, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+188]

; 91   : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?OnQueryDragIcon@CSUDOKUDlg@@IAEPAUHICON__@@XZ ENDP	; CSUDOKUDlg::OnQueryDragIcon
_TEXT	ENDS
; Function compile flags: /Odsp /RTCsu /ZI
; File c:\projets\sudoku\sudoku\sudoku\sudokudlg.cpp
;	COMDAT ?OnPaint@CSUDOKUDlg@@IAEXXZ
_TEXT	SEGMENT
_y$2 = -188						; size = 4
_x$3 = -176						; size = 4
_rect$4 = -164						; size = 16
_cyIcon$5 = -140					; size = 4
_cxIcon$6 = -128					; size = 4
_dc$7 = -116						; size = 84
_this$ = -24						; size = 4
__$ArrayPad$ = -16					; size = 4
__$EHRec$ = -12						; size = 12
?OnPaint@CSUDOKUDlg@@IAEXXZ PROC			; CSUDOKUDlg::OnPaint, COMDAT
; _this$ = ecx

; 62   : {

	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?OnPaint@CSUDOKUDlg@@IAEXXZ
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 372				; 00000174H
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-384]
	push	93					; 0000005dH
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	mov	DWORD PTR __$ArrayPad$[ebp], eax
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR _this$[ebp], ecx

; 63   : 	if (IsIconic())

	mov	ecx, DWORD PTR _this$[ebp]
	call	?IsIconic@CWnd@@QBEHXZ			; CWnd::IsIconic
	test	eax, eax
	je	$LN2@OnPaint

; 64   : 	{
; 65   : 		CPaintDC dc(this); // contexte de périphérique pour la peinture

	push	84					; 00000054H
	lea	ecx, DWORD PTR _dc$7[ebp]
	call	?__autoclassinit2@CPaintDC@@QAEXI@Z
	push	DWORD PTR _this$[ebp]
	lea	ecx, DWORD PTR _dc$7[ebp]
	call	??0CPaintDC@@QAE@PAVCWnd@@@Z		; CPaintDC::CPaintDC
	and	DWORD PTR __$EHRec$[ebp+8], 0

; 66   : 
; 67   : 		SendMessage(WM_ICONERASEBKGND, reinterpret_cast<WPARAM>(dc.GetSafeHdc()), 0);

	push	0
	lea	ecx, DWORD PTR _dc$7[ebp]
	call	?GetSafeHdc@CDC@@QBEPAUHDC__@@XZ	; CDC::GetSafeHdc
	push	eax
	push	39					; 00000027H
	mov	ecx, DWORD PTR _this$[ebp]
	call	?SendMessageW@CWnd@@QBEJIIJ@Z		; CWnd::SendMessageW

; 68   : 
; 69   : 		// Centrer l'icône dans le rectangle client
; 70   : 		int cxIcon = GetSystemMetrics(SM_CXICON);

	mov	esi, esp
	push	11					; 0000000bH
	call	DWORD PTR __imp__GetSystemMetrics@4
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _cxIcon$6[ebp], eax

; 71   : 		int cyIcon = GetSystemMetrics(SM_CYICON);

	mov	esi, esp
	push	12					; 0000000cH
	call	DWORD PTR __imp__GetSystemMetrics@4
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _cyIcon$5[ebp], eax

; 72   : 		CRect rect;

	lea	ecx, DWORD PTR _rect$4[ebp]
	call	??0CRect@@QAE@XZ			; CRect::CRect

; 73   : 		GetClientRect(&rect);

	lea	eax, DWORD PTR _rect$4[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?GetClientRect@CWnd@@QBEXPAUtagRECT@@@Z	; CWnd::GetClientRect

; 74   : 		int x = (rect.Width() - cxIcon + 1) / 2;

	lea	ecx, DWORD PTR _rect$4[ebp]
	call	?Width@CRect@@QBEHXZ			; CRect::Width
	sub	eax, DWORD PTR _cxIcon$6[ebp]
	inc	eax
	cdq
	sub	eax, edx
	sar	eax, 1
	mov	DWORD PTR _x$3[ebp], eax

; 75   : 		int y = (rect.Height() - cyIcon + 1) / 2;

	lea	ecx, DWORD PTR _rect$4[ebp]
	call	?Height@CRect@@QBEHXZ			; CRect::Height
	sub	eax, DWORD PTR _cyIcon$5[ebp]
	inc	eax
	cdq
	sub	eax, edx
	sar	eax, 1
	mov	DWORD PTR _y$2[ebp], eax

; 76   : 
; 77   : 		// Dessiner l'icône
; 78   : 		dc.DrawIcon(x, y, m_hIcon);

	mov	eax, DWORD PTR _this$[ebp]
	push	DWORD PTR [eax+188]
	push	DWORD PTR _y$2[ebp]
	push	DWORD PTR _x$3[ebp]
	lea	ecx, DWORD PTR _dc$7[ebp]
	call	?DrawIcon@CDC@@QAEHHHPAUHICON__@@@Z	; CDC::DrawIcon

; 79   : 	}

	or	DWORD PTR __$EHRec$[ebp+8], -1
	lea	ecx, DWORD PTR _dc$7[ebp]
	call	??1CPaintDC@@UAE@XZ			; CPaintDC::~CPaintDC

; 80   : 	else

	jmp	SHORT $LN3@OnPaint
$LN2@OnPaint:

; 81   : 	{
; 82   : 		CDialogEx::OnPaint();

	mov	ecx, DWORD PTR _this$[ebp]
	call	?OnPaint@CDialog@@IAEXXZ		; CDialog::OnPaint
$LN3@OnPaint:

; 83   : 	}
; 84   : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN10@OnPaint
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	mov	ecx, DWORD PTR __$ArrayPad$[ebp]
	xor	ecx, ebp
	call	@__security_check_cookie@4
	add	esp, 384				; 00000180H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
	npad	2
$LN10@OnPaint:
	DD	2
	DD	$LN9@OnPaint
$LN9@OnPaint:
	DD	-116					; ffffff8cH
	DD	84					; 00000054H
	DD	$LN6@OnPaint
	DD	-164					; ffffff5cH
	DD	16					; 00000010H
	DD	$LN7@OnPaint
$LN7@OnPaint:
	DB	114					; 00000072H
	DB	101					; 00000065H
	DB	99					; 00000063H
	DB	116					; 00000074H
	DB	0
$LN6@OnPaint:
	DB	100					; 00000064H
	DB	99					; 00000063H
	DB	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$?OnPaint@CSUDOKUDlg@@IAEXXZ$0:
	lea	ecx, DWORD PTR _dc$7[ebp]
	jmp	??1CPaintDC@@UAE@XZ			; CPaintDC::~CPaintDC
__ehhandler$?OnPaint@CSUDOKUDlg@@IAEXXZ:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-388]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	ecx, DWORD PTR [edx-4]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$?OnPaint@CSUDOKUDlg@@IAEXXZ
	jmp	___CxxFrameHandler3
text$x	ENDS
?OnPaint@CSUDOKUDlg@@IAEXXZ ENDP			; CSUDOKUDlg::OnPaint
; Function compile flags: /Odsp /RTCsu /ZI
; File c:\projets\sudoku\sudoku\sudoku\sudokudlg.cpp
;	COMDAT ?OnInitDialog@CSUDOKUDlg@@MAEHXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?OnInitDialog@CSUDOKUDlg@@MAEHXZ PROC			; CSUDOKUDlg::OnInitDialog, COMDAT
; _this$ = ecx

; 42   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	push	51					; 00000033H
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 43   : 	CDialogEx::OnInitDialog();

	mov	ecx, DWORD PTR _this$[ebp]
	call	?OnInitDialog@CDialog@@UAEHXZ		; CDialog::OnInitDialog

; 44   : 	EnableToolTips();

	push	1
	mov	ecx, DWORD PTR _this$[ebp]
	call	?EnableToolTips@CWnd@@QAEHH@Z		; CWnd::EnableToolTips

; 45   : 
; 46   : 	// Définir l'icône de cette boîte de dialogue.  L'infrastructure effectue cela automatiquement
; 47   : 	//  lorsque la fenêtre principale de l'application n'est pas une boîte de dialogue
; 48   : 	SetIcon(m_hIcon, TRUE);			// Définir une grande icône

	push	1
	mov	eax, DWORD PTR _this$[ebp]
	push	DWORD PTR [eax+188]
	mov	ecx, DWORD PTR _this$[ebp]
	call	?SetIcon@CWnd@@QAEPAUHICON__@@PAU2@H@Z	; CWnd::SetIcon

; 49   : 	SetIcon(m_hIcon, FALSE);		// Définir une petite icône

	push	0
	mov	eax, DWORD PTR _this$[ebp]
	push	DWORD PTR [eax+188]
	mov	ecx, DWORD PTR _this$[ebp]
	call	?SetIcon@CWnd@@QAEPAUHICON__@@PAU2@H@Z	; CWnd::SetIcon

; 50   : 
; 51   : 	// TODO: ajoutez ici une initialisation supplémentaire
; 52   : 	GetDlgItem(IDC_BUTTON1)->EnableWindow(FALSE);

	push	0
	push	1081					; 00000439H
	mov	ecx, DWORD PTR _this$[ebp]
	call	?GetDlgItem@CWnd@@QBEPAV1@H@Z		; CWnd::GetDlgItem
	mov	ecx, eax
	call	?EnableWindow@CWnd@@QAEHH@Z		; CWnd::EnableWindow

; 53   : 	::SetDlgItemTextW(m_hWnd, IDC_STATIC,_T(""));

	mov	esi, esp
	push	OFFSET ??_C@_11LOCGONAA@?$AA?$AA@
	push	-1
	mov	eax, DWORD PTR _this$[ebp]
	push	DWORD PTR [eax+32]
	call	DWORD PTR __imp__SetDlgItemTextW@12
	cmp	esi, esp
	call	__RTC_CheckEsp

; 54   : 	return TRUE;  // retourne TRUE, sauf si vous avez défini le focus sur un contrôle

	xor	eax, eax
	inc	eax

; 55   : }

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?OnInitDialog@CSUDOKUDlg@@MAEHXZ ENDP			; CSUDOKUDlg::OnInitDialog
_TEXT	ENDS
; Function compile flags: /Odsp /RTCsu /ZI
; File c:\projets\sudoku\sudoku\sudoku\sudokudlg.cpp
;	COMDAT ?DoDataExchange@CSUDOKUDlg@@MAEXPAVCDataExchange@@@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_pDX$ = 8						; size = 4
?DoDataExchange@CSUDOKUDlg@@MAEXPAVCDataExchange@@@Z PROC ; CSUDOKUDlg::DoDataExchange, COMDAT
; _this$ = ecx

; 25   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	push	51					; 00000033H
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 26   : 	CDialogEx::DoDataExchange(pDX);

	push	DWORD PTR _pDX$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	call	?DoDataExchange@CWnd@@MAEXPAVCDataExchange@@@Z ; CWnd::DoDataExchange

; 27   : }

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
?DoDataExchange@CSUDOKUDlg@@MAEXPAVCDataExchange@@@Z ENDP ; CSUDOKUDlg::DoDataExchange
_TEXT	ENDS
; Function compile flags: /Odsp /RTCsu /ZI
; File c:\projets\sudoku\sudoku\sudoku\sudokudlg.cpp
;	COMDAT ??0CSUDOKUDlg@@QAE@PAVCWnd@@@Z
_TEXT	SEGMENT
_this$ = -20						; size = 4
__$EHRec$ = -12						; size = 12
_pParent$ = 8						; size = 4
??0CSUDOKUDlg@@QAE@PAVCWnd@@@Z PROC			; CSUDOKUDlg::CSUDOKUDlg, COMDAT
; _this$ = ecx

; 19   : {

	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$??0CSUDOKUDlg@@QAE@PAVCWnd@@@Z
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-216]
	push	51					; 00000033H
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR _this$[ebp], ecx
	push	DWORD PTR _pParent$[ebp]
	push	102					; 00000066H
	mov	ecx, DWORD PTR _this$[ebp]
	call	??0CDialogEx@@QAE@IPAVCWnd@@@Z		; CDialogEx::CDialogEx
	and	DWORD PTR __$EHRec$[ebp+8], 0
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax], OFFSET ??_7CSUDOKUDlg@@6B@

; 20   : 	m_hIcon = AfxGetApp()->LoadIcon(IDR_MAINFRAME);

	push	128					; 00000080H
	call	?AfxGetApp@@YGPAVCWinApp@@XZ		; AfxGetApp
	mov	ecx, eax
	call	?LoadIconW@CWinApp@@QBEPAUHICON__@@I@Z	; CWinApp::LoadIconW
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx+188], eax

; 21   : 	//  Value_IDC_EDIT1 = 0;
; 22   : }

	or	DWORD PTR __$EHRec$[ebp+8], -1
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$??0CSUDOKUDlg@@QAE@PAVCWnd@@@Z$0:
	mov	ecx, DWORD PTR _this$[ebp]
	jmp	??1CDialogEx@@UAE@XZ
__ehhandler$??0CSUDOKUDlg@@QAE@PAVCWnd@@@Z:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-220]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$??0CSUDOKUDlg@@QAE@PAVCWnd@@@Z
	jmp	___CxxFrameHandler3
text$x	ENDS
??0CSUDOKUDlg@@QAE@PAVCWnd@@@Z ENDP			; CSUDOKUDlg::CSUDOKUDlg
; Function compile flags: /Odsp /RTCsu /ZI
;	COMDAT ??1CDialogEx@@UAE@XZ
_TEXT	SEGMENT
_this$ = -20						; size = 4
__$EHRec$ = -12						; size = 12
??1CDialogEx@@UAE@XZ PROC				; CDialogEx::~CDialogEx, COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$??1CDialogEx@@UAE@XZ
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-216]
	push	51					; 00000033H
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR _this$[ebp], ecx
	mov	DWORD PTR __$EHRec$[ebp+8], 1
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 176				; 000000b0H
	call	??1CDialogImpl@@MAE@XZ			; CDialogImpl::~CDialogImpl
	mov	BYTE PTR __$EHRec$[ebp+8], 0
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 164				; 000000a4H
	call	??1CBrush@@UAE@XZ			; CBrush::~CBrush
	or	DWORD PTR __$EHRec$[ebp+8], -1
	mov	ecx, DWORD PTR _this$[ebp]
	call	??1CDialog@@UAE@XZ			; CDialog::~CDialog
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 216				; 000000d8H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$??1CDialogEx@@UAE@XZ$0:
	mov	ecx, DWORD PTR _this$[ebp]
	jmp	??1CDialog@@UAE@XZ			; CDialog::~CDialog
__unwindfunclet$??1CDialogEx@@UAE@XZ$1:
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 164				; 000000a4H
	jmp	??1CBrush@@UAE@XZ			; CBrush::~CBrush
__ehhandler$??1CDialogEx@@UAE@XZ:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-220]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$??1CDialogEx@@UAE@XZ
	jmp	___CxxFrameHandler3
text$x	ENDS
??1CDialogEx@@UAE@XZ ENDP				; CDialogEx::~CDialogEx
; Function compile flags: /Odsp /RTCsu /ZI
;	COMDAT ?__autoclassinit2@CPaintDC@@QAEXI@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_classSize$ = 8						; size = 4
?__autoclassinit2@CPaintDC@@QAEXI@Z PROC		; CPaintDC::__autoclassinit2, COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	push	51					; 00000033H
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx
	push	DWORD PTR _classSize$[ebp]
	push	0
	push	DWORD PTR _this$[ebp]
	call	_memset
	add	esp, 12					; 0000000cH
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
?__autoclassinit2@CPaintDC@@QAEXI@Z ENDP		; CPaintDC::__autoclassinit2
_TEXT	ENDS
; Function compile flags: /Odsp /RTCsu /ZI
; File c:\program files (x86)\microsoft visual studio 12.0\vc\atlmfc\include\atltypes.h
;	COMDAT ?Height@CRect@@QBEHXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?Height@CRect@@QBEHXZ PROC				; CRect::Height, COMDAT
; _this$ = ecx

; 580  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	push	51					; 00000033H
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 581  : 	return bottom - top;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+12]
	sub	eax, DWORD PTR [ecx+4]

; 582  : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?Height@CRect@@QBEHXZ ENDP				; CRect::Height
_TEXT	ENDS
; Function compile flags: /Odsp /RTCsu /ZI
; File c:\program files (x86)\microsoft visual studio 12.0\vc\atlmfc\include\atltypes.h
;	COMDAT ?Width@CRect@@QBEHXZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
?Width@CRect@@QBEHXZ PROC				; CRect::Width, COMDAT
; _this$ = ecx

; 575  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	push	51					; 00000033H
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 576  : 	return right - left;

	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [eax+8]
	sub	eax, DWORD PTR [ecx]

; 577  : }

	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
?Width@CRect@@QBEHXZ ENDP				; CRect::Width
_TEXT	ENDS
; Function compile flags: /Odsp /RTCsu /ZI
; File c:\program files (x86)\microsoft visual studio 12.0\vc\atlmfc\include\atltypes.h
;	COMDAT ??0CRect@@QAE@XZ
_TEXT	SEGMENT
_this$ = -8						; size = 4
??0CRect@@QAE@XZ PROC					; CRect::CRect, COMDAT
; _this$ = ecx

; 527  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	push	51					; 00000033H
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 528  : 	left = 0;

	mov	eax, DWORD PTR _this$[ebp]
	and	DWORD PTR [eax], 0

; 529  : 	top = 0;

	mov	eax, DWORD PTR _this$[ebp]
	and	DWORD PTR [eax+4], 0

; 530  : 	right = 0;

	mov	eax, DWORD PTR _this$[ebp]
	and	DWORD PTR [eax+8], 0

; 531  : 	bottom = 0;

	mov	eax, DWORD PTR _this$[ebp]
	and	DWORD PTR [eax+12], 0

; 532  : }

	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	mov	esp, ebp
	pop	ebp
	ret	0
??0CRect@@QAE@XZ ENDP					; CRect::CRect
_TEXT	ENDS
; Function compile flags: /Odsp /RTCsu /ZI
; File c:\program files (x86)\microsoft visual studio 12.0\vc\atlmfc\include\atltrace.h
;	COMDAT ?RegisterCategory@CTrace@ATL@@SAXPB_WI@Z
_TEXT	SEGMENT
_pszCategory$ = 8					; size = 4
_nCategory$ = 12					; size = 4
?RegisterCategory@CTrace@ATL@@SAXPB_WI@Z PROC		; ATL::CTrace::RegisterCategory, COMDAT

; 262  : 	{

	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	push	48					; 00000030H
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd

; 263  : 		if (pszCategory == nullptr)

	cmp	DWORD PTR _pszCategory$[ebp], 0
	jne	SHORT $LN2@RegisterCa

; 264  : 		{
; 265  : 			return;

	jmp	$LN3@RegisterCa
$LN2@RegisterCa:

; 266  : 		}
; 267  : 
; 268  : 		if (m_nLastCategory >= MaxCategoryArray) 

	cmp	DWORD PTR ?m_nLastCategory@CTrace@ATL@@1IA, 32 ; ATL::CTrace::m_nLastCategory, 00000020H
	jb	SHORT $LN1@RegisterCa

; 269  : 		{
; 270  : 			ATLASSERT(false && "Too many categories defined");

	xor	eax, eax
	jne	SHORT $LN5@RegisterCa
	mov	esi, esp
	push	OFFSET ??_C@_1EO@EBPPKGOM@?$AAf?$AAa?$AAl?$AAs?$AAe?$AA?5?$AA?$CG?$AA?$CG?$AA?5?$AA?$CC?$AAT?$AAo?$AAo?$AA?5?$AAm?$AAa?$AAn?$AAy?$AA?5?$AAc?$AAa?$AAt?$AAe?$AAg?$AAo?$AAr?$AAi?$AAe?$AAs?$AA?5?$AAd?$AAe@
	push	OFFSET ??_C@_15GANGMFKL@?$AA?$CF?$AAs?$AA?$AA@
	push	0
	push	270					; 0000010eH
	push	OFFSET ??_C@_1KC@GEMPEEJK@?$AAc?$AA?3?$AA?2?$AAp?$AAr?$AAo?$AAg?$AAr?$AAa?$AAm?$AA?5?$AAf?$AAi?$AAl?$AAe?$AAs?$AA?5?$AA?$CI?$AAx?$AA8?$AA6?$AA?$CJ?$AA?2?$AAm?$AAi?$AAc?$AAr?$AAo?$AAs?$AAo?$AAf?$AAt@
	push	2
	call	DWORD PTR __imp___CrtDbgReportW
	add	esp, 24					; 00000018H
	cmp	esi, esp
	call	__RTC_CheckEsp
	cmp	eax, 1
	jne	SHORT $LN5@RegisterCa
	int	3
$LN5@RegisterCa:

; 271  : 			return;

	jmp	SHORT $LN3@RegisterCa
$LN1@RegisterCa:

; 272  : 		}
; 273  : 
; 274  : 		m_nMap[m_nLastCategory].nCategory = nCategory;

	imul	eax, DWORD PTR ?m_nLastCategory@CTrace@ATL@@1IA, 260 ; ATL::CTrace::m_nLastCategory
	mov	ecx, DWORD PTR _nCategory$[ebp]
	mov	DWORD PTR ?m_nMap@CTrace@ATL@@1PAUCategoryMap@12@A[eax], ecx

; 275  : #ifdef _UNICODE
; 276  : 		wcscpy_s(m_nMap[m_nLastCategory].categryName, MaxLengthOfCategoryName - 1, pszCategory);

	mov	esi, esp
	push	DWORD PTR _pszCategory$[ebp]
	push	127					; 0000007fH
	imul	eax, DWORD PTR ?m_nLastCategory@CTrace@ATL@@1IA, 260 ; ATL::CTrace::m_nLastCategory
	add	eax, OFFSET ?m_nMap@CTrace@ATL@@1PAUCategoryMap@12@A+4
	push	eax
	call	DWORD PTR __imp__wcscpy_s
	add	esp, 12					; 0000000cH
	cmp	esi, esp
	call	__RTC_CheckEsp

; 277  : #else
; 278  : 		wchar_t buffer[MaxLengthOfCategoryName] = { 0 };	
; 279  : 		swprintf_s(buffer, MaxLengthOfCategoryName - 1, L"%S", pszCategory);
; 280  : 		wcscpy_s(m_nMap[m_nLastCategory].categryName, MaxLengthOfCategoryName - 1, buffer);
; 281  : #endif
; 282  : 	
; 283  : 		m_nLastCategory++;

	mov	eax, DWORD PTR ?m_nLastCategory@CTrace@ATL@@1IA ; ATL::CTrace::m_nLastCategory
	inc	eax
	mov	DWORD PTR ?m_nLastCategory@CTrace@ATL@@1IA, eax ; ATL::CTrace::m_nLastCategory
$LN3@RegisterCa:

; 284  : 	}

	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?RegisterCategory@CTrace@ATL@@SAXPB_WI@Z ENDP		; ATL::CTrace::RegisterCategory
_TEXT	ENDS
; Function compile flags: /Odsp /RTCsu /ZI
; File c:\program files (x86)\microsoft visual studio 12.0\vc\atlmfc\include\atltrace.h
;	COMDAT ??__EatlTraceString@ATL@@YAXXZ
text$di	SEGMENT
??__EatlTraceString@ATL@@YAXXZ PROC			; ATL::`dynamic initializer for 'atlTraceString'', COMDAT

; 113  : __declspec(selectany) CTraceCategoryEx<CTraceCategoryEx<>::TraceString> atlTraceString(_T("atlTraceString"));

	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	push	48					; 00000030H
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	push	OFFSET ??_C@_1BO@GMLILNDJ@?$AAa?$AAt?$AAl?$AAT?$AAr?$AAa?$AAc?$AAe?$AAS?$AAt?$AAr?$AAi?$AAn?$AAg?$AA?$AA@
	mov	ecx, OFFSET ?atlTraceString@ATL@@3V?$CTraceCategoryEx@$0CAAAA@$0A@@1@A ; ATL::atlTraceString
	call	??0?$CTraceCategoryEx@$0CAAAA@$0A@@ATL@@QAE@PB_W@Z ; ATL::CTraceCategoryEx<131072,0>::CTraceCategoryEx<131072,0>
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
??__EatlTraceString@ATL@@YAXXZ ENDP			; ATL::`dynamic initializer for 'atlTraceString''
text$di	ENDS
; Function compile flags: /Odsp /RTCsu /ZI
; File c:\program files (x86)\microsoft visual studio 12.0\vc\atlmfc\include\atltrace.h
;	COMDAT ??0?$CTraceCategoryEx@$0CAAAA@$0A@@ATL@@QAE@PB_W@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_pszCategoryName$ = 8					; size = 4
??0?$CTraceCategoryEx@$0CAAAA@$0A@@ATL@@QAE@PB_W@Z PROC	; ATL::CTraceCategoryEx<131072,0>::CTraceCategoryEx<131072,0>, COMDAT
; _this$ = ecx

; 388  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	push	51					; 00000033H
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 389  : 	CTrace::RegisterCategory(pszCategoryName, traceCategory);

	push	131072					; 00020000H
	push	DWORD PTR _pszCategoryName$[ebp]
	call	?RegisterCategory@CTrace@ATL@@SAXPB_WI@Z ; ATL::CTrace::RegisterCategory
	pop	ecx
	pop	ecx

; 390  : }

	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??0?$CTraceCategoryEx@$0CAAAA@$0A@@ATL@@QAE@PB_W@Z ENDP	; ATL::CTraceCategoryEx<131072,0>::CTraceCategoryEx<131072,0>
_TEXT	ENDS
; Function compile flags: /Odsp /RTCsu /ZI
; File c:\program files (x86)\microsoft visual studio 12.0\vc\atlmfc\include\atltrace.h
;	COMDAT ??__EatlTraceException@ATL@@YAXXZ
text$di	SEGMENT
??__EatlTraceException@ATL@@YAXXZ PROC			; ATL::`dynamic initializer for 'atlTraceException'', COMDAT

; 109  : __declspec(selectany) CTraceCategoryEx<CTraceCategoryEx<>::TraceException> atlTraceException(_T("atlTraceException"));

	push	ebp
	mov	ebp, esp
	sub	esp, 192				; 000000c0H
	push	ebx
	push	esi
	push	edi
	lea	edi, DWORD PTR [ebp-192]
	push	48					; 00000030H
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	push	OFFSET ??_C@_1CE@IMMADNAP@?$AAa?$AAt?$AAl?$AAT?$AAr?$AAa?$AAc?$AAe?$AAE?$AAx?$AAc?$AAe?$AAp?$AAt?$AAi?$AAo?$AAn?$AA?$AA@
	mov	ecx, OFFSET ?atlTraceException@ATL@@3V?$CTraceCategoryEx@$0CAAA@$0A@@1@A ; ATL::atlTraceException
	call	??0?$CTraceCategoryEx@$0CAAA@$0A@@ATL@@QAE@PB_W@Z ; ATL::CTraceCategoryEx<8192,0>::CTraceCategoryEx<8192,0>
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 192				; 000000c0H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
??__EatlTraceException@ATL@@YAXXZ ENDP			; ATL::`dynamic initializer for 'atlTraceException''
text$di	ENDS
; Function compile flags: /Odsp /RTCsu /ZI
; File c:\program files (x86)\microsoft visual studio 12.0\vc\atlmfc\include\atltrace.h
;	COMDAT ??0?$CTraceCategoryEx@$0CAAA@$0A@@ATL@@QAE@PB_W@Z
_TEXT	SEGMENT
_this$ = -8						; size = 4
_pszCategoryName$ = 8					; size = 4
??0?$CTraceCategoryEx@$0CAAA@$0A@@ATL@@QAE@PB_W@Z PROC	; ATL::CTraceCategoryEx<8192,0>::CTraceCategoryEx<8192,0>, COMDAT
; _this$ = ecx

; 388  : {

	push	ebp
	mov	ebp, esp
	sub	esp, 204				; 000000ccH
	push	ebx
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-204]
	push	51					; 00000033H
	pop	ecx
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	DWORD PTR _this$[ebp], ecx

; 389  : 	CTrace::RegisterCategory(pszCategoryName, traceCategory);

	push	8192					; 00002000H
	push	DWORD PTR _pszCategoryName$[ebp]
	call	?RegisterCategory@CTrace@ATL@@SAXPB_WI@Z ; ATL::CTrace::RegisterCategory
	pop	ecx
	pop	ecx

; 390  : }

	mov	eax, DWORD PTR _this$[ebp]
	pop	edi
	pop	esi
	pop	ebx
	add	esp, 204				; 000000ccH
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??0?$CTraceCategoryEx@$0CAAA@$0A@@ATL@@QAE@PB_W@Z ENDP	; ATL::CTraceCategoryEx<8192,0>::CTraceCategoryEx<8192,0>
_TEXT	ENDS
END
